#ifdef _WIN32
#include "engine/download_engine.h"
#include "common/airi_text.h"
#include <windows.h>
#include <winhttp.h>
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <vector>
#pragma comment(lib,"winhttp.lib")
namespace airi { namespace {
std::wstring W(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring o(n,L'\0');MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n);return o;}
std::string U8(const std::wstring&s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string o(n,'\0');WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n,nullptr,nullptr);return o;}
struct Url{std::wstring host,path;INTERNET_PORT port{};bool https{};};
bool parse(const std::string&u,Url&o){auto w=W(u);URL_COMPONENTS c{sizeof(c)};c.dwHostNameLength=(DWORD)-1;c.dwUrlPathLength=(DWORD)-1;c.dwExtraInfoLength=(DWORD)-1;if(!WinHttpCrackUrl(w.c_str(),0,0,&c))return false;o.host.assign(c.lpszHostName,c.dwHostNameLength);o.path.assign(c.lpszUrlPath,c.dwUrlPathLength);if(c.dwExtraInfoLength)o.path.append(c.lpszExtraInfo,c.dwExtraInfoLength);if(o.path.empty())o.path=L"/";o.port=c.nPort;o.https=c.nScheme==INTERNET_SCHEME_HTTPS;return true;}
struct Handles{HINTERNET session{},connect{},request{};~Handles(){if(request)WinHttpCloseHandle(request);if(connect)WinHttpCloseHandle(connect);if(session)WinHttpCloseHandle(session);}};
bool open_req(const DownloadRequest&r,const wchar_t*verb,Handles&h,const std::wstring&range=L""){Url u;if(!parse(r.url,u))return false;h.session=WinHttpOpen(L"AIRI Download Manager/2.1",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0);if(!h.session)return false;h.connect=WinHttpConnect(h.session,u.host.c_str(),u.port,0);if(!h.connect)return false;DWORD flags=u.https?WINHTTP_FLAG_SECURE:0;h.request=WinHttpOpenRequest(h.connect,verb,u.path.c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,flags);if(!h.request)return false;std::wstring hdr=L"Accept: */*\r\n";if(!r.cookie.empty())hdr+=L"Cookie: "+W(r.cookie)+L"\r\n";if(!r.referer.empty())hdr+=L"Referer: "+W(r.referer)+L"\r\n";if(!r.origin.empty())hdr+=L"Origin: "+W(r.origin)+L"\r\n";if(!range.empty())hdr+=L"Range: bytes="+range+L"\r\n";if(!r.user_agent.empty())WinHttpAddRequestHeaders(h.request,(L"User-Agent: "+W(r.user_agent)).c_str(),-1L,WINHTTP_ADDREQ_FLAG_REPLACE|WINHTTP_ADDREQ_FLAG_ADD);if(!hdr.empty())WinHttpAddRequestHeaders(h.request,hdr.c_str(),-1L,WINHTTP_ADDREQ_FLAG_ADD);return WinHttpSendRequest(h.request,WINHTTP_NO_ADDITIONAL_HEADERS,0,WINHTTP_NO_REQUEST_DATA,0,0,0)&&WinHttpReceiveResponse(h.request,nullptr);}
DWORD status(HINTERNET q){DWORD v=0,n=sizeof(v);WinHttpQueryHeaders(q,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,nullptr,&v,&n,nullptr);return v;}
std::uint64_t content_length(HINTERNET q){wchar_t b[128]{};DWORD n=sizeof(b);if(!WinHttpQueryHeaders(q,WINHTTP_QUERY_CONTENT_LENGTH,nullptr,b,&n,nullptr))return 0;try{return std::stoull(b);}catch(...){return 0;}}
std::wstring disposition_name(HINTERNET q){wchar_t b[2048]{};DWORD n=sizeof(b);if(!WinHttpQueryHeaders(q,WINHTTP_QUERY_CONTENT_DISPOSITION,nullptr,b,&n,nullptr))return{};std::wstring s=b;auto p=s.find(L"filename=");if(p==std::wstring::npos)return{};p+=9;if(p<s.size()&&s[p]=='\"'){auto e=s.find(L'\"',++p);return s.substr(p,e-p);}auto e=s.find(L';',p);return s.substr(p,e==std::wstring::npos?s.size()-p:e-p);}
}
const char* status_name(DownloadStatus x){switch(x){case DownloadStatus::Queued:return"Queued";case DownloadStatus::Probing:return"Probing";case DownloadStatus::Downloading:return"Downloading";case DownloadStatus::Paused:return"Paused";case DownloadStatus::Completed:return"Completed";case DownloadStatus::Failed:return"Failed";case DownloadStatus::Cancelled:return"Cancelled";}return"Unknown";}
DownloadTask::DownloadTask(std::uint64_t id,DownloadRequest r,Callback cb):id_(id),req_(std::move(r)),cb_(std::move(cb)){s_.id=id_;s_.url=req_.url;s_.filename=req_.filename;}
DownloadTask::~DownloadTask(){cancelled_=true;paused_=false;if(th_.joinable())th_.join();}
void DownloadTask::start(){th_=std::thread([this]{run();});}
void DownloadTask::pause(){paused_=true;{std::lock_guard lk(m_);s_.status=DownloadStatus::Paused;}emit();}
void DownloadTask::resume(){paused_=false;{std::lock_guard lk(m_);if(s_.status==DownloadStatus::Paused)s_.status=DownloadStatus::Downloading;}emit();}
void DownloadTask::cancel(){cancelled_=true;paused_=false;{std::lock_guard lk(m_);s_.status=DownloadStatus::Cancelled;}emit();}
DownloadSnapshot DownloadTask::snapshot()const{std::lock_guard lk(m_);auto x=s_;x.downloaded_bytes=downloaded_;if(x.total_bytes)x.progress_percent=(int)std::min<std::uint64_t>(100,downloaded_*100/x.total_bytes);return x;}
void DownloadTask::emit(){if(cb_)cb_(snapshot());}
void DownloadTask::fail(std::string e){{std::lock_guard lk(m_);s_.status=DownloadStatus::Failed;s_.error=std::move(e);}emit();}
void DownloadTask::run(){{std::lock_guard lk(m_);s_.status=DownloadStatus::Probing;}emit();if(!probe())return;if(cancelled_)return;{std::lock_guard lk(m_);s_.status=DownloadStatus::Downloading;}emit();bool ok=ranges_&&s_.total_bytes>chunk_?segmented():sequential();if(ok&&!cancelled_){{std::lock_guard lk(m_);s_.status=DownloadStatus::Completed;s_.progress_percent=100;}emit();}}
bool DownloadTask::probe(){Handles h;if(!open_req(req_,L"GET",h,L"0-0")){fail("Connection/probe failed");return false;}auto st=status(h.request);ranges_=st==206;std::uint64_t total=0;if(st==206){wchar_t b[256]{};DWORD n=sizeof(b);if(WinHttpQueryHeaders(h.request,WINHTTP_QUERY_CONTENT_RANGE,nullptr,b,&n,nullptr)){std::wstring v=b;auto slash=v.find_last_of(L'/');if(slash!=std::wstring::npos)try{total=std::stoull(v.substr(slash+1));}catch(...){}}}if(!total)total=content_length(h.request);if(st>=400||!total){fail("Server rejected request or size unavailable (HTTP "+std::to_string(st)+")");return false;}std::string fn=req_.filename;if(fn.empty()){auto d=disposition_name(h.request);fn=d.empty()?text::filename_from_url_utf8(req_.url):U8(d);}fn=text::sanitize_filename_utf8(fn);auto out=req_.save_directory/fn;std::filesystem::create_directories(req_.save_directory);for(int i=1;std::filesystem::exists(out);++i){auto stem=out.stem().wstring(),ext=out.extension().wstring();out=req_.save_directory/(stem+L" ("+std::to_wstring(i)+L")"+ext);} {std::lock_guard lk(m_);s_.filename=fn;s_.total_bytes=total;s_.output_path=out;}return true;}
void DownloadTask::update_speed(){static thread_local auto last=std::chrono::steady_clock::now();static thread_local std::uint64_t prev=0;auto now=std::chrono::steady_clock::now();auto ms=std::chrono::duration_cast<std::chrono::milliseconds>(now-last).count();if(ms>=400){auto cur=downloaded_.load();{std::lock_guard lk(m_);s_.bytes_per_second=(cur-prev)*1000.0/ms;}prev=cur;last=now;emit();}}
bool DownloadTask::segmented(){auto snap=snapshot();HANDLE f=CreateFileW(snap.output_path.c_str(),GENERIC_WRITE|GENERIC_READ,FILE_SHARE_READ,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(f==INVALID_HANDLE_VALUE){fail("Cannot create output file");return false;}LARGE_INTEGER sz{};sz.QuadPart=(LONGLONG)snap.total_bytes;SetFilePointerEx(f,sz,nullptr,FILE_BEGIN);SetEndOfFile(f);std::uint64_t chunks=(snap.total_bytes+chunk_-1)/chunk_;std::atomic<std::uint64_t> next{0};int workers=std::clamp(req_.connections,1,64);std::atomic<bool> bad{false};std::vector<std::thread> ts;for(int k=0;k<workers;k++)ts.emplace_back([&,this]{std::vector<char>buf(256*1024);while(!cancelled_&&!bad){while(paused_&&!cancelled_)Sleep(80);auto idx=next.fetch_add(1);if(idx>=chunks)break;auto begin=idx*chunk_,end=std::min<std::uint64_t>(snap.total_bytes-1,begin+chunk_-1);Handles h;if(!open_req(req_,L"GET",h,std::to_wstring(begin)+L"-"+std::to_wstring(end))||status(h.request)!=206){bad=true;break;}std::uint64_t off=begin;for(;;){while(paused_&&!cancelled_)Sleep(80);if(cancelled_)break;DWORD avail=0;if(!WinHttpQueryDataAvailable(h.request,&avail)){bad=true;break;}if(!avail)break;DWORD got=0;if(!WinHttpReadData(h.request,buf.data(),(DWORD)std::min<std::size_t>(buf.size(),avail),&got)||!got){bad=true;break;}{std::lock_guard lk(file_m_);LARGE_INTEGER p{};p.QuadPart=(LONGLONG)off;SetFilePointerEx(f,p,nullptr,FILE_BEGIN);DWORD wrote=0;if(!WriteFile(f,buf.data(),got,&wrote,nullptr)||wrote!=got){bad=true;break;}}off+=got;downloaded_+=got;update_speed();}}});for(auto&t:ts)t.join();CloseHandle(f);if(cancelled_)return false;if(bad){fail("Segmented download failed");return false;}return downloaded_==snap.total_bytes;}
bool DownloadTask::sequential(){auto snap=snapshot();Handles h;if(!open_req(req_,L"GET",h)||status(h.request)>=400){fail("Download request failed");return false;}HANDLE f=CreateFileW(snap.output_path.c_str(),GENERIC_WRITE,FILE_SHARE_READ,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(f==INVALID_HANDLE_VALUE){fail("Cannot create output file");return false;}std::vector<char>buf(256*1024);while(!cancelled_){while(paused_&&!cancelled_)Sleep(80);DWORD avail=0;if(!WinHttpQueryDataAvailable(h.request,&avail)){CloseHandle(f);fail("Network read failed");return false;}if(!avail)break;DWORD got=0;if(!WinHttpReadData(h.request,buf.data(),(DWORD)std::min<std::size_t>(buf.size(),avail),&got)||!got){CloseHandle(f);fail("Network read failed");return false;}DWORD wrote=0;if(!WriteFile(f,buf.data(),got,&wrote,nullptr)||wrote!=got){CloseHandle(f);fail("Disk write failed");return false;}downloaded_+=got;update_speed();}CloseHandle(f);return !cancelled_;}
DownloadManager::DownloadManager(Callback cb):cb_(std::move(cb)){}
std::shared_ptr<DownloadTask>DownloadManager::add(DownloadRequest r){auto t=std::make_shared<DownloadTask>(next_++,std::move(r),cb_);{std::lock_guard lk(m_);tasks_.push_back(t);}t->start();return t;}
std::vector<DownloadSnapshot>DownloadManager::snapshots()const{std::lock_guard lk(m_);std::vector<DownloadSnapshot>v;for(auto&t:tasks_)v.push_back(t->snapshot());return v;}
std::shared_ptr<DownloadTask>DownloadManager::find(std::uint64_t id)const{std::lock_guard lk(m_);for(auto&t:tasks_)if(t->snapshot().id==id)return t;return{};}
}
#endif
