package id.airi.os;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.speech.*;
import android.speech.tts.TextToSpeech;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import java.util.*;

public class AssistantActivity extends Activity implements TextToSpeech.OnInitListener {
    private static final int REQ_AUDIO=77; private SpeechRecognizer recognizer; private TextToSpeech tts; private TextView status; private boolean ttsReady;
    @Override protected void onCreate(Bundle b){super.onCreate(b);buildUi();tts=new TextToSpeech(this,this);if(SpeechRecognizer.isRecognitionAvailable(this)){recognizer=SpeechRecognizer.createSpeechRecognizer(this);recognizer.setRecognitionListener(listener);}}
    private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(24),dp(42),dp(24),dp(24));root.setBackgroundColor(Color.rgb(247,245,239));root.addView(text("Irzuqni",36,true));TextView sub=text("AIRI Voice Assistant",13,false);sub.setTextColor(Color.DKGRAY);root.addView(sub,margin(-1,-2,0,2,0,24));status=text("Sentuh tombol dan bicara",17,false);status.setGravity(Gravity.CENTER);root.addView(status,margin(-1,dp(88),0,0,0,18));TextView listen=button("🎙  Dengarkan saya");listen.setOnClickListener(v->startListening());root.addView(listen,margin(-1,dp(54),0,0,0,10));LinearLayout row=new LinearLayout(this);TextView on=button("Always Listen ON");on.setOnClickListener(v->enableAlways());row.addView(on,new LinearLayout.LayoutParams(0,dp(48),1));TextView off=button("OFF");off.setOnClickListener(v->{stopService(new Intent(this,IrzuqniListenService.class));status.setText("Mode selalu mendengarkan dimatikan.");});LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(0,dp(48),1);op.setMargins(dp(8),0,0,0);row.addView(off,op);root.addView(row,margin(-1,-2,0,0,0,14));TextView ex=text("Saat Always Listen aktif, ucapkan nama ‘Irzuqni’ atau ‘AIRI’ diikuti perintah, misalnya: “Irzuqni buka kamera”. Notifikasi mikrofon akan tetap terlihat.",13,false);ex.setTextColor(Color.rgb(90,90,90));root.addView(ex);setContentView(root);}
    private void enableAlways(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_AUDIO);return;}Intent s=new Intent(this,IrzuqniListenService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);status.setText("Always Listen aktif. Panggil: ‘Irzuqni…’");}
    private void startListening(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_AUDIO);return;}if(recognizer==null){say("Pengenalan suara tidak tersedia.");return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"id-ID");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);status.setText("Saya mendengarkan…");recognizer.startListening(i);}
    private final RecognitionListener listener=new RecognitionListener(){public void onReadyForSpeech(Bundle b){status.setText("Silakan bicara…");}public void onBeginningOfSpeech(){}public void onRmsChanged(float f){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){status.setText("Memahami perintah…");}public void onError(int e){status.setText("Belum terdengar jelas. Coba lagi.");}public void onPartialResults(Bundle b){ArrayList<String> r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(r!=null&&!r.isEmpty())status.setText(r.get(0));}public void onEvent(int e,Bundle b){}public void onResults(Bundle b){ArrayList<String> r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(r!=null&&!r.isEmpty())execute(r.get(0));}};
    private void execute(String raw){String s=raw.toLowerCase(Locale.ROOT).trim();status.setText("“"+raw+"”");if(s.contains("kamera")){say("Baik, saya buka kamera.");try{startActivity(new Intent("android.media.action.IMAGE_CAPTURE"));}catch(Exception e){openApp("camera");}return;}if(s.contains("wifi")||s.contains("wi-fi")){say("Membuka Wi-Fi.");startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));return;}if(s.contains("bluetooth")){say("Membuka Bluetooth.");startActivity(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS));return;}if(s.contains("pengaturan")){say("Membuka pengaturan.");startActivity(new Intent(Settings.ACTION_SETTINGS));return;}if(s.contains("jam berapa")){String t=new java.text.SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date());say("Sekarang pukul "+t.replace(':','.'));return;}if(s.startsWith("buka ")){String n=s.substring(5).trim();if(openApp(n))say("Membuka "+n);else say("Aplikasi "+n+" tidak ditemukan.");return;}if(s.startsWith("cari ")){String q=s.substring(5).trim();Intent i=new Intent(Intent.ACTION_WEB_SEARCH);i.putExtra("query",q);try{startActivity(i);say("Saya carikan "+q);}catch(Exception e){say("Pencarian tidak tersedia.");}return;}say("Saya mendengar "+raw+".");}
    private boolean openApp(String n){Intent m=new Intent(Intent.ACTION_MAIN,null);m.addCategory(Intent.CATEGORY_LAUNCHER);for(android.content.pm.ResolveInfo r:getPackageManager().queryIntentActivities(m,0)){CharSequence l=r.loadLabel(getPackageManager());if(l!=null&&l.toString().toLowerCase(Locale.ROOT).contains(n.toLowerCase(Locale.ROOT))){Intent x=getPackageManager().getLaunchIntentForPackage(r.activityInfo.packageName);if(x!=null){startActivity(x);return true;}}}return false;}
    private void say(String s){status.setText(s);if(ttsReady)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"irzuqni");}
    @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS){ttsReady=true;tts.setLanguage(new Locale("id","ID"));tts.setPitch(1.08f);tts.setSpeechRate(.93f);say("Assalamualaikum. Saya Irzuqni. Ada yang bisa saya bantu?");}}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_AUDIO&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)enableAlways();}
    @Override protected void onDestroy(){if(recognizer!=null)recognizer.destroy();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
    private TextView text(String s,float z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(28,32,35));v.setTypeface(android.graphics.Typeface.create("sans",b?1:0));return v;}private TextView button(String s){TextView v=text(s,14,true);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(Color.rgb(48,86,117));d.setCornerRadius(dp(26));v.setBackground(d);return v;}private LinearLayout.LayoutParams margin(int w,int h,int l,int t,int r,int b){int ww=w==-1?ViewGroup.LayoutParams.MATCH_PARENT:(w==-2?ViewGroup.LayoutParams.WRAP_CONTENT:w),hh=h==-1?ViewGroup.LayoutParams.MATCH_PARENT:(h==-2?ViewGroup.LayoutParams.WRAP_CONTENT:h);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ww,hh);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
