package id.airi.os;

import android.app.Activity;
import android.app.role.RoleManager;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.GridLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.text.Editable;
import android.text.TextWatcher;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(247,245,239), INK=Color.rgb(25,29,32), MUTED=Color.rgb(103,106,108), BLUE=Color.rgb(48,86,117), CARD=Color.rgb(255,255,252);
    private GridLayout appGrid; private PackageManager pm; private final List<AppEntry> apps=new ArrayList<>();
    @Override protected void onCreate(Bundle b){super.onCreate(b);Window w=getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(BG);if(Build.VERSION.SDK_INT>=23)w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);pm=getPackageManager();build();loadApps();}
    @Override protected void onResume(){super.onResume();if(appGrid!=null)loadApps();}
    private void build(){
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(16),dp(20),dp(28));root.setBackgroundColor(BG);scroll.addView(root,new ScrollView.LayoutParams(-1,-2));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView brand=text("AIRI OS",14,BLUE,true);brand.setLetterSpacing(.15f);top.addView(brand,new LinearLayout.LayoutParams(0,dp(40),1));TextView home=pill("AIRI Home");home.setOnClickListener(v->requestHome());top.addView(home,new LinearLayout.LayoutParams(-2,dp(38)));root.addView(top);
        TextView device=text("INTELLIGENCE EDITION  •  "+Build.MODEL,10,MUTED,true);device.setLetterSpacing(.11f);root.addView(device,lp(-1,-2,0,0,0,8));
        TextView clock=text(new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()),52,INK,true);root.addView(clock);TextView date=text(new SimpleDateFormat("EEEE, d MMMM",new Locale("id","ID")).format(new Date()),15,MUTED,false);root.addView(date,lp(-1,-2,0,-6,0,12));
        TextView island=text("●  Irzuqni ready   •   AI tools online",12,Color.WHITE,true);island.setGravity(Gravity.CENTER);island.setBackground(round(Color.rgb(30,34,38),24,Color.rgb(30,34,38),0));island.setOnClickListener(v->startActivity(new Intent(this,IntelligenceHubActivity.class)));root.addView(island,lp(-1,dp(44),0,0,0,14));
        LinearLayout ai=new LinearLayout(this);ai.setGravity(Gravity.CENTER_VERTICAL);ai.setPadding(dp(18),dp(15),dp(14),dp(15));ai.setBackground(round(Color.rgb(236,242,247),24,Color.rgb(211,222,231),1));LinearLayout aiText=new LinearLayout(this);aiText.setOrientation(LinearLayout.VERTICAL);aiText.addView(text("Irzuqni",20,INK,true));aiText.addView(text("Voice • Smart Text • Gallery AI • Search",12,MUTED,false));ai.addView(aiText,new LinearLayout.LayoutParams(0,-2,1));TextView mic=pill("✦ Bicara");mic.setOnClickListener(v->startActivity(new Intent(this,AssistantActivity.class)));ai.addView(mic,new LinearLayout.LayoutParams(-2,dp(40)));ai.setOnClickListener(v->startActivity(new Intent(this,IntelligenceHubActivity.class)));root.addView(ai,lp(-1,-2,0,0,0,14));
        EditText search=new EditText(this);search.setSingleLine(true);search.setHint("Cari aplikasi…");search.setTextColor(INK);search.setHintTextColor(Color.rgb(140,140,138));search.setTextSize(15);search.setPadding(dp(17),0,dp(17),0);search.setBackground(round(CARD,22,Color.rgb(226,224,218),1));root.addView(search,new LinearLayout.LayoutParams(-1,dp(50)));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});
        root.addView(section("AIRI Intelligence"),lp(-1,-2,0,20,0,8));GridLayout hub=new GridLayout(this);hub.setColumnCount(2);addTool(hub,"AI Hub","Semua fitur AI",()->startActivity(new Intent(this,IntelligenceHubActivity.class)));addTool(hub,"Smart Text","Ringkas & translate",()->startActivity(new Intent(this,SmartTextActivity.class)));addTool(hub,"Gallery AI","Photo intelligence",()->startActivity(new Intent(this,GalleryLabActivity.class)));addTool(hub,"Irzuqni","Voice assistant",()->startActivity(new Intent(this,AssistantActivity.class)));addTool(hub,"Smart Eraser","Object cleanup",()->startActivity(new Intent(this,SmartEraserActivity.class)));addTool(hub,"Circle Search","Visual search",()->startActivity(new Intent(this,CircleSearchActivity.class)));root.addView(hub);
        root.addView(section("Quick Center"),lp(-1,-2,0,18,0,8));GridLayout quick=new GridLayout(this);quick.setColumnCount(3);addQuick(quick,"Camera",this::openCamera);addQuick(quick,"Performance",()->startActivity(new Intent(this,PerformanceCenterActivity.class)));addQuick(quick,"Wallpaper",()->startActivity(new Intent(this,WallpaperLabActivity.class)));addQuick(quick,"Wi-Fi",()->safeStart(new Intent(Settings.ACTION_WIFI_SETTINGS)));addQuick(quick,"Bluetooth",()->safeStart(new Intent(Settings.ACTION_BLUETOOTH_SETTINGS)));addQuick(quick,"Settings",()->safeStart(new Intent(Settings.ACTION_SETTINGS)));root.addView(quick);
        root.addView(section("Aplikasi"),lp(-1,-2,0,20,0,4));root.addView(text("AIRI Icon System • lightweight launcher shell",11,MUTED,false),lp(-1,-2,0,0,0,10));appGrid=new GridLayout(this);appGrid.setColumnCount(4);root.addView(appGrid,new LinearLayout.LayoutParams(-1,-2));TextView foot=text("AIRI OS v3.0 • Intelligence Edition • RMX1851",10,MUTED,false);foot.setGravity(Gravity.CENTER);root.addView(foot,lp(-1,dp(48),0,18,0,0));setContentView(scroll);
    }
    private void addTool(GridLayout g,String title,String sub,Runnable action){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(12),dp(12));c.setBackground(round(CARD,20,Color.rgb(228,227,221),1));c.addView(text(title,15,INK,true));c.addView(text(sub,11,MUTED,false));c.setOnClickListener(v->action.run());GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(72);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));g.addView(c,p);}private void addQuick(GridLayout g,String s,Runnable a){TextView v=text(s,12,INK,true);v.setGravity(Gravity.CENTER);v.setBackground(round(CARD,18,Color.rgb(230,228,223),1));v.setOnClickListener(x->a.run());GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(54);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(3),dp(3),dp(3),dp(3));g.addView(v,p);}
    private void openCamera(){Intent i=new Intent("android.media.action.IMAGE_CAPTURE");try{startActivity(i);}catch(Exception e){for(AppEntry a:apps)if(a.label.toLowerCase(Locale.ROOT).contains("camera")||a.label.toLowerCase(Locale.ROOT).contains("kamera")){Intent l=pm.getLaunchIntentForPackage(a.pkg);if(l!=null){startActivity(l);return;}}}}private void safeStart(Intent i){try{startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}}
    private void loadApps(){apps.clear();Intent i=new Intent(Intent.ACTION_MAIN,null);i.addCategory(Intent.CATEGORY_LAUNCHER);for(ResolveInfo r:pm.queryIntentActivities(i,0)){if(r.activityInfo==null||getPackageName().equals(r.activityInfo.packageName))continue;CharSequence cs=r.loadLabel(pm);apps.add(new AppEntry(cs==null?r.activityInfo.packageName:cs.toString(),r.activityInfo.packageName));}Collections.sort(apps,(a,b)->a.label.compareToIgnoreCase(b.label));render("");}private void render(String filter){if(appGrid==null)return;appGrid.removeAllViews();String n=filter==null?"":filter.trim().toLowerCase(Locale.ROOT);for(AppEntry a:apps){if(!n.isEmpty()&&!a.label.toLowerCase(Locale.ROOT).contains(n))continue;appGrid.addView(tile(a),tileLp());}}private View tile(AppEntry a){LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setGravity(Gravity.CENTER_HORIZONTAL);FrameLayout badge=new FrameLayout(this);badge.setBackground(round(Color.rgb(238,241,243),18,Color.rgb(220,225,228),1));ImageView iv=new ImageView(this);try{iv.setImageDrawable(pm.getApplicationIcon(a.pkg));}catch(Exception e){iv.setImageResource(android.R.drawable.sym_def_app_icon);}iv.setPadding(dp(8),dp(8),dp(8),dp(8));badge.addView(iv,new FrameLayout.LayoutParams(-1,-1));t.addView(badge,new LinearLayout.LayoutParams(dp(54),dp(54)));TextView l=text(a.label,10.5f,INK,false);l.setGravity(Gravity.CENTER);l.setMaxLines(2);t.addView(l,lp(-1,dp(32),0,4,0,0));t.setOnClickListener(v->{Intent x=pm.getLaunchIntentForPackage(a.pkg);if(x!=null)startActivity(x);});return t;}private GridLayout.LayoutParams tileLp(){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(98);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(1),dp(2),dp(1),dp(2));return p;}
    private void requestHome(){if(Build.VERSION.SDK_INT>=29){RoleManager rm=(RoleManager)getSystemService(Context.ROLE_SERVICE);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_HOME)&&!rm.isRoleHeld(RoleManager.ROLE_HOME)){startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_HOME),91);return;}}safeStart(new Intent(Settings.ACTION_HOME_SETTINGS));}
    private TextView section(String s){return text(s,18,INK,true);}private TextView pill(String s){TextView v=text(s,12,Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setPadding(dp(13),0,dp(13),0);v.setBackground(round(BLUE,20,BLUE,0));return v;}private TextView text(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));return v;}private GradientDrawable round(int fill,int radius,int stroke,int sw){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(sw>0)d.setStroke(dp(sw),stroke);return d;}private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){int ww=w==-1?ViewGroup.LayoutParams.MATCH_PARENT:(w==-2?ViewGroup.LayoutParams.WRAP_CONTENT:w),hh=h==-1?ViewGroup.LayoutParams.MATCH_PARENT:(h==-2?ViewGroup.LayoutParams.WRAP_CONTENT:h);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ww,hh);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private static class AppEntry{String label,pkg;AppEntry(String l,String p){label=l;pkg=p;}}
}
