package id.airi.os;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.animation.DecelerateInterpolator;
import android.widget.FrameLayout;
import android.widget.GridLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class MainActivity extends Activity {
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final List<LauncherCatalog.App> apps=new ArrayList<>();
    private PackageManager pm;private GridLayout appGrid;private LinearLayout dock;private TextView clock,islandText;private float downX,downY;private long downAt;private int enterIndex=0;
    @Override protected void onCreate(Bundle b){super.onCreate(b);pm=getPackageManager();Window w=getWindow();w.setStatusBarColor(Color.TRANSPARENT);w.setNavigationBarColor(Color.rgb(244,247,251));w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);build();loadApps();tick();}
    @Override protected void onResume(){super.onResume();if(appGrid!=null)loadApps();}
    @Override protected void onDestroy(){handler.removeCallbacksAndMessages(null);super.onDestroy();}
    @Override public void onBackPressed(){}
    @Override public boolean dispatchTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){downX=e.getX();downY=e.getY();downAt=System.currentTimeMillis();}else if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-downX,dy=e.getY()-downY;long dt=System.currentTimeMillis()-downAt;if(dt<800){if(Math.abs(dy)>dp(110)&&Math.abs(dy)>Math.abs(dx)*1.15f){if(dy<0)open(new Intent(this,AppLibraryActivity.class));else if(downX<getResources().getDisplayMetrics().widthPixels/2f)open(new Intent(this,NotificationCenterActivity.class));else open(new Intent(this,ControlCenterActivity.class));}else if(Math.abs(dx)>dp(125)&&Math.abs(dx)>Math.abs(dy)*1.2f){open(new Intent(this,dx<0?FavoriteWorkspaceActivity.class:LauncherSettingsActivity.class));}}}return super.dispatchTouchEvent(e);}

    private void build(){final int INK=Color.rgb(24,28,35),MUTED=Color.rgb(103,111,124),ACCENT=Color.rgb(82,123,255),WHITE=Color.WHITE;FrameLayout stage=new FrameLayout(this);stage.addView(new HyperFlowBackdropView(this),new FrameLayout.LayoutParams(-1,-1));LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(17),dp(28),dp(17),dp(112));root.setLongClickable(true);root.setOnLongClickListener(v->{open(new Intent(this,LauncherSettingsActivity.class));return true;});stage.addView(root,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout status=new LinearLayout(this);status.setGravity(Gravity.CENTER_VERTICAL);clock=text(now("HH:mm"),14,INK,true);status.addView(clock,new LinearLayout.LayoutParams(0,dp(34),1));TextView brand=text("AIRI Fusion v20",11,INK,true);brand.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);status.addView(brand,new LinearLayout.LayoutParams(0,dp(34),1));root.addView(status);
        islandText=text("✦  Ultimate Fusion  •  Ready",11,WHITE,true);islandText.setGravity(Gravity.CENTER);islandText.setBackground(round(Color.rgb(35,38,45),999));islandText.setElevation(dp(13));islandText.setOnClickListener(v->open(new Intent(this,FutureCoreActivity.class)));press(islandText);LinearLayout.LayoutParams ip=lp(dp(230),dp(42),0,2,0,12);ip.gravity=Gravity.CENTER_HORIZONTAL;root.addView(enter(islandText),ip);if(MotionEngine.islandPulse(this))pulseIsland();
        LinearLayout widgets=new LinearLayout(this);widgets.setGravity(Gravity.CENTER);LinearLayout timeCard=whiteCard();timeCard.setGravity(Gravity.CENTER_VERTICAL);timeCard.addView(text(new SimpleDateFormat("EEEE",new Locale("id","ID")).format(new Date()),11,MUTED,true));timeCard.addView(text(now("HH:mm"),40,INK,false));timeCard.addView(text(new SimpleDateFormat("d MMMM",new Locale("id","ID")).format(new Date()),12,MUTED,false));widgets.addView(enter(timeCard),new LinearLayout.LayoutParams(0,dp(126),1.18f));LinearLayout side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(126),.82f);sp.setMargins(dp(9),0,0,0);widgets.addView(side,sp);LinearLayout searchCard=miniCard("⌕","Universal","Search everything",Color.rgb(77,139,255));searchCard.setOnClickListener(v->open(new Intent(this,UniversalSearchActivity.class)));side.addView(enter(searchCard),new LinearLayout.LayoutParams(-1,0,1));LinearLayout focus=miniCard("★","Focus","Favorites + habits",Color.rgb(145,96,240));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,0,1);fp.setMargins(0,dp(8),0,0);side.addView(enter(focus),fp);focus.setOnClickListener(v->open(new Intent(this,FavoriteWorkspaceActivity.class)));root.addView(widgets);
        LinearLayout smart=new LinearLayout(this);smart.setGravity(Gravity.CENTER);smart.setPadding(dp(7),dp(7),dp(7),dp(7));smart.setBackground(round(Color.argb(186,255,255,255),dp(25)));smart.setElevation(dp(9));smartAction(smart,"⌕","Search",()->open(new Intent(this,UniversalSearchActivity.class)));smartAction(smart,"★","Focus",()->open(new Intent(this,FavoriteWorkspaceActivity.class)));smartAction(smart,"▰","Dock",()->open(new Intent(this,DockEditorActivity.class)));smartAction(smart,"◉","Themes",()->open(new Intent(this,ThemeCenterActivity.class)));smartAction(smart,"⚡","Boost",()->open(new Intent(this,PerformanceCenterActivity.class)));root.addView(enter(smart),lp(-1,dp(68),0,12,0,10));
        LinearLayout appsHeader=new LinearLayout(this);appsHeader.setGravity(Gravity.CENTER_VERTICAL);appsHeader.addView(text("Smart Apps",16,INK,true),new LinearLayout.LayoutParams(0,dp(30),1));TextView all=text("Library  ›",11,ACCENT,true);all.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);all.setOnClickListener(v->open(new Intent(this,AppLibraryActivity.class)));appsHeader.addView(all,new LinearLayout.LayoutParams(-2,dp(30)));root.addView(appsHeader);appGrid=new GridLayout(this);appGrid.setColumnCount(LauncherPrefs.columns(this));root.addView(appGrid,new LinearLayout.LayoutParams(-1,dp(208)));
        TextView search=text("⌕   Universal Search",12,Color.rgb(83,91,105),true);search.setGravity(Gravity.CENTER);search.setBackground(round(Color.argb(205,255,255,255),dp(28)));search.setElevation(dp(8));search.setOnClickListener(v->open(new Intent(this,UniversalSearchActivity.class)));press(search);LinearLayout.LayoutParams sr=lp(dp(184),dp(42),0,5,0,4);sr.gravity=Gravity.CENTER_HORIZONTAL;root.addView(search,sr);TextView gesture=text("← Focus   → Settings   ↑ Apps   ↓ Notifications / Control",8.2f,Color.rgb(115,121,131),false);gesture.setGravity(Gravity.CENTER);root.addView(gesture,new LinearLayout.LayoutParams(-1,dp(22)));
        dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(9),dp(8),dp(9),dp(8));dock.setBackground(round(Color.argb(224,255,255,255),dp(32)));dock.setElevation(dp(20));FrameLayout.LayoutParams dl=new FrameLayout.LayoutParams(-1,dp(78),Gravity.BOTTOM);dl.setMargins(dp(19),0,dp(19),dp(16));stage.addView(dock,dl);setContentView(stage);}

    private void loadApps(){apps.clear();apps.addAll(LauncherCatalog.load(this,false));final List<String> top=AppLaunchStats.top(this,64);final boolean predictive=LauncherPrefs.suggestions(this);Collections.sort(apps,new Comparator<LauncherCatalog.App>(){public int compare(LauncherCatalog.App a,LauncherCatalog.App b){boolean af=LauncherPrefs.isFavorite(MainActivity.this,a.pkg),bf=LauncherPrefs.isFavorite(MainActivity.this,b.pkg);if(af!=bf)return af?-1:1;if(predictive){int ia=top.indexOf(a.pkg),ib=top.indexOf(b.pkg);if(ia>=0||ib>=0){if(ia<0)return 1;if(ib<0)return -1;if(ia!=ib)return Integer.compare(ia,ib);}}return a.label.compareToIgnoreCase(b.label);}});renderApps();renderDock();}
    private void renderApps(){if(appGrid==null)return;appGrid.removeAllViews();int cols=LauncherPrefs.columns(this);appGrid.setColumnCount(cols);int count=Math.min(cols*2,apps.size());for(int n=0;n<count;n++)appGrid.addView(appTile(apps.get(n),true),gridParams(LauncherPrefs.labels(this)?94:72));}
    private View appTile(LauncherCatalog.App a,boolean home){LinearLayout tile=new LinearLayout(this);tile.setOrientation(LinearLayout.VERTICAL);tile.setGravity(Gravity.CENTER);FrameLayout iconBox=new FrameLayout(this);ImageView iv=new ImageView(this);try{iv.setImageDrawable(AiriIconPack.drawable(this,pm.getApplicationIcon(a.pkg),dp(60)));}catch(Exception e){iv.setImageResource(android.R.drawable.sym_def_app_icon);}iv.setPadding(dp(2),dp(2),dp(2),dp(2));iconBox.addView(iv,new FrameLayout.LayoutParams(-1,-1));if(LauncherPrefs.isFavorite(this,a.pkg)){TextView star=text("★",10,Color.rgb(75,110,245),true);star.setGravity(Gravity.CENTER);star.setBackground(round(Color.WHITE,dp(10)));iconBox.addView(star,new FrameLayout.LayoutParams(dp(20),dp(20),Gravity.TOP|Gravity.LEFT));}int c=LauncherPrefs.badges(this)?AiriNotificationListener.count(a.pkg):0;if(c>0){TextView badge=text(c>99?"99+":String.valueOf(c),8,Color.WHITE,true);badge.setGravity(Gravity.CENTER);badge.setBackground(round(Color.rgb(235,70,70),dp(10)));iconBox.addView(badge,new FrameLayout.LayoutParams(dp(c>9?25:20),dp(20),Gravity.TOP|Gravity.RIGHT));}tile.addView(iconBox,new LinearLayout.LayoutParams(dp(60),dp(60)));if(LauncherPrefs.labels(this)){TextView name=text(a.label,9,Color.rgb(37,42,50),true);name.setGravity(Gravity.CENTER);name.setMaxLines(1);tile.addView(name,new LinearLayout.LayoutParams(-1,dp(25)));}tile.setOnClickListener(v->launch(a.pkg));tile.setOnLongClickListener(v->{boolean next=!LauncherPrefs.isFavorite(this,a.pkg);LauncherPrefs.favorite(this,a.pkg,next);Toast.makeText(this,next?a.label+" pinned":a.label+" unpinned",Toast.LENGTH_SHORT).show();loadApps();return true;});press(tile);return enter(tile);}
    private GridLayout.LayoutParams gridParams(int h){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(h);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(2),dp(1),dp(2),dp(1));return p;}
    private void renderDock(){if(dock==null)return;dock.removeAllViews();List<String> slots=new ArrayList<>(LauncherPrefs.dock(this));if(LauncherPrefs.smartDock(this)){List<String> candidates=new ArrayList<>();candidates.addAll(LauncherPrefs.favorites(this));for(String p:AppLaunchStats.top(this,32))if(!candidates.contains(p))candidates.add(p);for(LauncherCatalog.App a:apps)if(!candidates.contains(a.pkg))candidates.add(a.pkg);for(int i=0;i<5;i++)if(slots.get(i).isEmpty()&&i<candidates.size())slots.set(i,candidates.get(i));}
        for(int i=0;i<5;i++){String pkg=slots.get(i);if(pkg==null||pkg.isEmpty()){TextView plus=text("＋",23,Color.rgb(55,61,70),true);plus.setGravity(Gravity.CENTER);plus.setBackground(round(Color.argb(110,255,255,255),dp(22)));plus.setOnClickListener(v->open(new Intent(this,DockEditorActivity.class)));press(plus);dock.addView(plus,dockParams());continue;}FrameLayout box=new FrameLayout(this);ImageView iv=new ImageView(this);try{iv.setImageDrawable(AiriIconPack.drawable(this,pm.getApplicationIcon(pkg),dp(55)));}catch(Exception e){iv.setImageResource(android.R.drawable.sym_def_app_icon);}box.addView(iv,new FrameLayout.LayoutParams(-1,-1));int c=LauncherPrefs.badges(this)?AiriNotificationListener.count(pkg):0;if(c>0){TextView badge=text(c>99?"99+":String.valueOf(c),7.5f,Color.WHITE,true);badge.setGravity(Gravity.CENTER);badge.setBackground(round(Color.rgb(235,70,70),dp(9)));box.addView(badge,new FrameLayout.LayoutParams(dp(c>9?23:19),dp(19),Gravity.TOP|Gravity.RIGHT));}box.setOnClickListener(v->launch(pkg));box.setOnLongClickListener(v->{open(new Intent(this,DockEditorActivity.class));return true;});press(box);dock.addView(box,dockParams());}}
    private LinearLayout.LayoutParams dockParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(58),1);p.setMargins(dp(4),0,dp(4),0);return p;}
    private void launch(String pkg){try{Intent x=pm.getLaunchIntentForPackage(pkg);if(x!=null){AppLaunchStats.record(this,pkg);open(x);}}catch(Exception ignored){}}

    private LinearLayout whiteCard(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(14));c.setBackground(round(Color.argb(214,255,255,255),dp(28)));c.setElevation(dp(10));return c;}
    private LinearLayout miniCard(String big,String title,String sub,int accent){LinearLayout c=whiteCard();c.setPadding(dp(12),dp(7),dp(12),dp(7));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView b=text(big,18,accent,true);row.addView(b,new LinearLayout.LayoutParams(0,-2,1));row.addView(text("↗",12,Color.rgb(91,99,112),true));c.addView(row);c.addView(text(title,10,Color.rgb(33,38,46),true));c.addView(text(sub,8.5f,Color.rgb(107,114,126),false));press(c);return c;}
    private void smartAction(LinearLayout row,String glyph,String label,Runnable r){LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);TextView g=text(glyph,18,Color.rgb(42,47,56),true);g.setGravity(Gravity.CENTER);item.addView(g,new LinearLayout.LayoutParams(-1,dp(29)));TextView l=text(label,8.5f,Color.rgb(84,91,103),true);l.setGravity(Gravity.CENTER);item.addView(l,new LinearLayout.LayoutParams(-1,dp(18)));item.setOnClickListener(v->r.run());press(item);row.addView(item,new LinearLayout.LayoutParams(0,dp(54),1));}
    private android.graphics.drawable.GradientDrawable round(int color,float radius){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(color);g.setCornerRadius(radius);g.setStroke(dp(1),Color.argb(70,255,255,255));return g;}
    private void press(View v){v.setClickable(true);v.setOnTouchListener((x,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)x.animate().scaleX(MotionEngine.pressScale(this)).scaleY(MotionEngine.pressScale(this)).setDuration(MotionEngine.pressDownMs(this)).start();else if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL)x.animate().scaleX(MotionEngine.releaseScale(this)).scaleY(MotionEngine.releaseScale(this)).setDuration(MotionEngine.releaseMs(this)).withEndAction(()->x.animate().scaleX(1).scaleY(1).setDuration(MotionEngine.settleMs(this)).setInterpolator(new DecelerateInterpolator(2f)).start()).start();return false;});}
    private View enter(View v){v.setAlpha(0);v.setTranslationY(dp(MotionEngine.enterOffsetDp(this)));int delay=Math.min(420,enterIndex++*MotionEngine.staggerMs(this));v.animate().alpha(1).translationY(0).setStartDelay(delay).setDuration(MotionEngine.enterMs(this)).setInterpolator(new DecelerateInterpolator(1.7f)).start();return v;}
    private void pulseIsland(){handler.postDelayed(new Runnable(){public void run(){if(islandText==null||!MotionEngine.islandPulse(MainActivity.this))return;float s=MotionEngine.ULTRA.equals(MotionEngine.mode(MainActivity.this))?1.05f:1.025f;islandText.animate().scaleX(s).scaleY(s).setDuration(500).withEndAction(()->islandText.animate().scaleX(1).scaleY(1).setDuration(650).start()).start();handler.postDelayed(this,3200);}},1000);}
    private void open(Intent i){try{startActivity(i);String t=MotionEngine.transition(this);if(MotionEngine.FADE.equals(t))overridePendingTransition(android.R.anim.fade_in,android.R.anim.fade_out);else if(MotionEngine.SLIDE.equals(t))overridePendingTransition(android.R.anim.slide_in_left,android.R.anim.slide_out_right);else overridePendingTransition(android.R.anim.fade_in,android.R.anim.fade_out);}catch(Exception ignored){}}
    private void tick(){handler.post(new Runnable(){public void run(){if(clock!=null)clock.setText(now("HH:mm"));handler.postDelayed(this,30000);}});}private String now(String f){return new SimpleDateFormat(f,Locale.getDefault()).format(new Date());}
    private TextView text(String s,float z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));return v;}
    private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){int ww=w==-1?ViewGroup.LayoutParams.MATCH_PARENT:(w==-2?ViewGroup.LayoutParams.WRAP_CONTENT:w),hh=h==-1?ViewGroup.LayoutParams.MATCH_PARENT:(h==-2?ViewGroup.LayoutParams.WRAP_CONTENT:h);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ww,hh);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
