package id.airi.os;

import android.app.Activity;import android.app.role.RoleManager;import android.content.Context;import android.content.Intent;import android.content.pm.PackageManager;import android.content.pm.ResolveInfo;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RadialGradient;import android.graphics.Shader;import android.graphics.Typeface;import android.graphics.drawable.Drawable;import android.graphics.drawable.GradientDrawable;import android.os.Build;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.provider.Settings;import android.view.Gravity;import android.view.MotionEvent;import android.view.View;import android.view.ViewGroup;import android.view.Window;import android.view.animation.DecelerateInterpolator;import android.widget.EditText;import android.widget.FrameLayout;import android.widget.GridLayout;import android.widget.ImageView;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.text.Editable;import android.text.TextWatcher;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity{
    private static final int INK=Color.rgb(18,27,37), MUTED=Color.rgb(81,99,114), BLUE=Color.rgb(43,102,160), DARK=Color.rgb(10,14,19);
    private final Handler h=new Handler(Looper.getMainLooper());private final List<AppEntry> apps=new ArrayList<>();private PackageManager pm;private GridLayout appGrid;private TextView clock,island;private int enterIndex=0;
    @Override protected void onCreate(Bundle b){super.onCreate(b);Window w=getWindow();w.setStatusBarColor(Color.TRANSPARENT);w.setNavigationBarColor(Color.rgb(218,235,247));if(Build.VERSION.SDK_INT>=23)w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);pm=getPackageManager();build();loadApps();tick();}
    @Override protected void onResume(){super.onResume();if(appGrid!=null)loadApps();}
    @Override protected void onDestroy(){h.removeCallbacksAndMessages(null);super.onDestroy();}

    private void build(){
        FrameLayout stage=new FrameLayout(this);stage.addView(new DepthWallpaper(this),new FrameLayout.LayoutParams(-1,-1));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setOverScrollMode(View.OVER_SCROLL_NEVER);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(8),dp(18),dp(122));scroll.addView(root,new ScrollView.LayoutParams(-1,-2));stage.addView(scroll,new FrameLayout.LayoutParams(-1,-1));

        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView brand=text("AIRI",13,INK,true);brand.setLetterSpacing(.20f);top.addView(brand,new LinearLayout.LayoutParams(0,dp(36),1));TextView v=glassText("Liquid Depth 26.6",11,INK,AiriGlassDrawable.CLEAR);press(v);v.setOnClickListener(x->requestHome());top.addView(v,new LinearLayout.LayoutParams(-2,dp(36)));root.addView(enter(top));

        island=text("✦  Irzuqni",12,Color.WHITE,true);island.setGravity(Gravity.CENTER);island.setBackground(AiriGlassDrawable.make(this,28,AiriGlassDrawable.DARK));island.setElevation(dp(12));press(island);island.setOnClickListener(x->open(new Intent(this,AssistantActivity.class)));LinearLayout.LayoutParams ip=lp(dp(166),dp(44),0,4,0,13);ip.gravity=Gravity.CENTER_HORIZONTAL;root.addView(enter(island),ip);pulse();

        clock=text(now("HH:mm"),68,INK,true);clock.setGravity(Gravity.CENTER);clock.setLetterSpacing(-.03f);root.addView(enter(clock));TextView date=text(new SimpleDateFormat("EEEE, d MMMM",new Locale("id","ID")).format(new Date()),15,MUTED,true);date.setGravity(Gravity.CENTER);root.addView(enter(date),lp(-1,-2,0,-10,0,18));

        LinearLayout widgets=new LinearLayout(this);widgets.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout intel=glassPanel(AiriGlassDrawable.REGULAR,30);intel.setOrientation(LinearLayout.VERTICAL);intel.setPadding(dp(18),dp(16),dp(16),dp(16));intel.addView(text("AIRI INTELLIGENCE",10,MUTED,true));intel.addView(text("Irzuqni",25,INK,true));intel.addView(text("Voice • Vision • Smart Text",11,MUTED,false));TextView state=text("● ready",11,BLUE,true);intel.addView(state,lp(-1,-2,0,7,0,0));press(intel);intel.setOnClickListener(x->open(new Intent(this,IntelligenceHubActivity.class)));widgets.addView(intel,new LinearLayout.LayoutParams(0,dp(126),1));
        LinearLayout perf=glassPanel(AiriGlassDrawable.BLUE,30);perf.setOrientation(LinearLayout.VERTICAL);perf.setGravity(Gravity.CENTER);TextView bolt=text("⚡",30,Color.WHITE,true);bolt.setGravity(Gravity.CENTER);perf.addView(bolt);TextView p1=text("Performance",11,Color.WHITE,true);p1.setGravity(Gravity.CENTER);perf.addView(p1);TextView p2=text("optimized",10,Color.argb(210,255,255,255),false);p2.setGravity(Gravity.CENTER);perf.addView(p2);press(perf);perf.setOnClickListener(x->open(new Intent(this,PerformanceCenterActivity.class)));LinearLayout.LayoutParams pperf=new LinearLayout.LayoutParams(dp(112),dp(126));pperf.setMargins(dp(11),0,0,0);widgets.addView(perf,pperf);root.addView(enter(widgets));

        EditText search=new EditText(this);search.setSingleLine(true);search.setHint("⌕  Search");search.setTextColor(INK);search.setHintTextColor(Color.rgb(91,108,122));search.setTextSize(15);search.setPadding(dp(18),0,dp(18),0);search.setBackground(AiriGlassDrawable.make(this,27,AiriGlassDrawable.CLEAR));search.setElevation(dp(8));root.addView(enter(search),lp(-1,dp(52),0,14,0,13));search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){render(s.toString());}public void afterTextChanged(Editable e){}});

        GridLayout airi=new GridLayout(this);airi.setColumnCount(4);addFeature(airi,"✦","Irzuqni",AssistantActivity.class,AiriGlassDrawable.DARK);addFeature(airi,"Aa","Smart Text",SmartTextActivity.class,AiriGlassDrawable.REGULAR);addFeature(airi,"◉","Gallery",GalleryLabActivity.class,AiriGlassDrawable.BLUE);addFeature(airi,"⌕","Circle",CircleSearchActivity.class,AiriGlassDrawable.CLEAR);addFeature(airi,"✧","Eraser",SmartEraserActivity.class,AiriGlassDrawable.REGULAR);addFeature(airi,"◐","Wallpaper",WallpaperLabActivity.class,AiriGlassDrawable.BLUE);addFeature(airi,"⚡","Boost",PerformanceCenterActivity.class,AiriGlassDrawable.DARK);addFeature(airi,"AI","AI Hub",IntelligenceHubActivity.class,AiriGlassDrawable.CLEAR);root.addView(enter(airi));

        LinearLayout libHead=new LinearLayout(this);libHead.setGravity(Gravity.CENTER_VERTICAL);TextView lib=text("App Library",18,INK,true);libHead.addView(lib,new LinearLayout.LayoutParams(0,dp(42),1));TextView count=glassText("all apps",10,MUTED,AiriGlassDrawable.CLEAR);libHead.addView(count,new LinearLayout.LayoutParams(-2,dp(32)));root.addView(enter(libHead),lp(-1,-2,0,12,0,2));appGrid=new GridLayout(this);appGrid.setColumnCount(4);root.addView(appGrid,new LinearLayout.LayoutParams(-1,-2));

        LinearLayout dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(dp(8),dp(8),dp(8),dp(8));dock.setBackground(AiriGlassDrawable.make(this,34,AiriGlassDrawable.REGULAR));dock.setElevation(dp(20));addDock(dock,"📷",this::openCamera);addDock(dock,"✦",()->open(new Intent(this,AssistantActivity.class)));addDock(dock,"◉",()->open(new Intent(this,GalleryLabActivity.class)));addDock(dock,"⚙",()->safeStart(new Intent(Settings.ACTION_SETTINGS)));FrameLayout.LayoutParams dockLp=new FrameLayout.LayoutParams(-1,dp(84),Gravity.BOTTOM);dockLp.setMargins(dp(22),0,dp(22),dp(18));stage.addView(dock,dockLp);
        setContentView(stage);
    }

    private LinearLayout glassPanel(int type,int radius){LinearLayout l=new LinearLayout(this);l.setBackground(AiriGlassDrawable.make(this,radius,type));l.setElevation(dp(type==AiriGlassDrawable.BLUE?14:11));return l;}
    private TextView glassText(String s,float z,int c,int type){TextView t=text(s,z,c,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),0,dp(12),0);t.setBackground(AiriGlassDrawable.make(this,22,type));t.setElevation(dp(7));return t;}
    private void addFeature(GridLayout g,String glyph,String label,Class<?> cls,int type){LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setGravity(Gravity.CENTER);TextView icon=text(glyph,22,type==AiriGlassDrawable.DARK||type==AiriGlassDrawable.BLUE?Color.WHITE:INK,true);icon.setGravity(Gravity.CENTER);icon.setBackground(AiriGlassDrawable.make(this,23,type));icon.setElevation(dp(9));t.addView(icon,new LinearLayout.LayoutParams(dp(61),dp(61)));TextView l=text(label,10.5f,INK,true);l.setGravity(Gravity.CENTER);l.setMaxLines(1);t.addView(l,lp(-1,dp(28),0,4,0,0));press(t);t.setOnClickListener(x->open(new Intent(this,cls)));GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(98);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(2),dp(3),dp(2),dp(3));g.addView(t,p);}
    private void addDock(LinearLayout d,String glyph,Runnable r){TextView x=text(glyph,24,INK,true);x.setGravity(Gravity.CENTER);x.setBackground(AiriGlassDrawable.make(this,24,AiriGlassDrawable.CLEAR));x.setElevation(dp(7));press(x);x.setOnClickListener(v->r.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(60),1);p.setMargins(dp(4),0,dp(4),0);d.addView(x,p);}

    private void loadApps(){apps.clear();Intent i=new Intent(Intent.ACTION_MAIN,null);i.addCategory(Intent.CATEGORY_LAUNCHER);for(ResolveInfo r:pm.queryIntentActivities(i,0)){if(r.activityInfo==null||getPackageName().equals(r.activityInfo.packageName))continue;CharSequence cs=r.loadLabel(pm);apps.add(new AppEntry(cs==null?r.activityInfo.packageName:cs.toString(),r.activityInfo.packageName));}Collections.sort(apps,(a,b)->a.label.compareToIgnoreCase(b.label));render("");}
    private void render(String filter){if(appGrid==null)return;appGrid.removeAllViews();String n=filter==null?"":filter.trim().toLowerCase(Locale.ROOT);int idx=0;for(AppEntry a:apps){if(!n.isEmpty()&&!a.label.toLowerCase(Locale.ROOT).contains(n))continue;View t=appTile(a);appGrid.addView(t,tileLp());t.setAlpha(0);t.setScaleX(.83f);t.setScaleY(.83f);t.setTranslationY(dp(14));t.animate().alpha(1).scaleX(1).scaleY(1).translationY(0).setStartDelay(Math.min(230,idx++*13)).setDuration(310).setInterpolator(new DecelerateInterpolator(1.8f)).start();}}
    private View appTile(AppEntry a){LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.setGravity(Gravity.CENTER_HORIZONTAL);FrameLayout badge=new FrameLayout(this);badge.setBackground(AiriGlassDrawable.make(this,23,AiriGlassDrawable.CLEAR));badge.setElevation(dp(8));ImageView iv=new ImageView(this);try{iv.setImageDrawable(pm.getApplicationIcon(a.pkg));}catch(Exception e){iv.setImageResource(android.R.drawable.sym_def_app_icon);}iv.setPadding(dp(6),dp(6),dp(6),dp(6));badge.addView(iv,new FrameLayout.LayoutParams(-1,-1));t.addView(badge,new LinearLayout.LayoutParams(dp(62),dp(62)));TextView l=text(a.label,10,INK,true);l.setGravity(Gravity.CENTER);l.setMaxLines(1);t.addView(l,lp(-1,dp(28),0,4,0,0));press(t);t.setOnClickListener(v->{Intent x=pm.getLaunchIntentForPackage(a.pkg);if(x!=null)open(x);});return t;}
    private GridLayout.LayoutParams tileLp(){GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(99);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(1),dp(2),dp(1),dp(2));return p;}

    private void press(View v){v.setClickable(true);v.setOnTouchListener((x,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN){x.animate().scaleX(.91f).scaleY(.91f).translationY(dp(2)).setDuration(75).start();}else if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){x.animate().scaleX(1.025f).scaleY(1.025f).translationY(0).setDuration(125).withEndAction(()->x.animate().scaleX(1).scaleY(1).setDuration(170).setInterpolator(new DecelerateInterpolator(2f)).start()).start();}return false;});}
    private View enter(View v){v.setAlpha(0);v.setTranslationY(dp(18));v.setScaleX(.985f);v.setScaleY(.985f);int delay=Math.min(360,enterIndex++*38);v.animate().alpha(1).translationY(0).scaleX(1).scaleY(1).setStartDelay(delay).setDuration(430).setInterpolator(new DecelerateInterpolator(1.7f)).start();return v;}
    private void pulse(){h.postDelayed(new Runnable(){public void run(){if(island==null)return;island.animate().scaleX(1.04f).scaleY(1.04f).setDuration(800).withEndAction(()->island.animate().scaleX(1).scaleY(1).setDuration(900).start()).start();h.postDelayed(this,2700);}},900);}
    private void tick(){h.post(new Runnable(){public void run(){if(clock!=null)clock.setText(now("HH:mm"));h.postDelayed(this,30000);}});}private String now(String f){return new SimpleDateFormat(f,Locale.getDefault()).format(new Date());}
    private void open(Intent i){try{startActivity(i);overridePendingTransition(android.R.anim.fade_in,android.R.anim.fade_out);}catch(Exception ignored){}}private void openCamera(){try{open(new Intent("android.media.action.IMAGE_CAPTURE"));}catch(Exception ignored){}}private void safeStart(Intent i){try{open(i);}catch(Exception e){open(new Intent(Settings.ACTION_SETTINGS));}}private void requestHome(){if(Build.VERSION.SDK_INT>=29){RoleManager rm=(RoleManager)getSystemService(Context.ROLE_SERVICE);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_HOME)&&!rm.isRoleHeld(RoleManager.ROLE_HOME)){startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_HOME),91);return;}}safeStart(new Intent(Settings.ACTION_HOME_SETTINGS));}
    private TextView text(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));return v;}private LinearLayout.LayoutParams lp(int w,int hh,int l,int t,int r,int b){int ww=w==-1?ViewGroup.LayoutParams.MATCH_PARENT:(w==-2?ViewGroup.LayoutParams.WRAP_CONTENT:w),h2=hh==-1?ViewGroup.LayoutParams.MATCH_PARENT:(hh==-2?ViewGroup.LayoutParams.WRAP_CONTENT:hh);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ww,h2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private static class AppEntry{String label,pkg;AppEntry(String l,String p){label=l;pkg=p;}}

    private static class DepthWallpaper extends View{
        private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final float d;DepthWallpaper(Context c){super(c);d=getResources().getDisplayMetrics().density;setLayerType(View.LAYER_TYPE_SOFTWARE,null);}protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();c.drawColor(Color.rgb(231,241,248));blob(c,w*.18f,h*.16f,260*d,Color.rgb(255,232,202),185);blob(c,w*.86f,h*.24f,230*d,Color.rgb(131,194,235),175);blob(c,w*.42f,h*.57f,280*d,Color.rgb(246,250,255),200);blob(c,w*.92f,h*.76f,250*d,Color.rgb(173,217,241),150);blob(c,w*.08f,h*.88f,210*d,Color.rgb(255,242,219),150);}private void blob(Canvas c,float x,float y,float r,int col,int alpha){p.setShader(new RadialGradient(x,y,r,new int[]{Color.argb(alpha,Color.red(col),Color.green(col),Color.blue(col)),Color.TRANSPARENT},new float[]{0,.72f},Shader.TileMode.CLAMP));c.drawCircle(x,y,r,p);p.setShader(null);}}
}
