#include "common/airi_json.h"
#include <cctype>
#include <sstream>
namespace airi::json {
std::string escape(const std::string& value){std::ostringstream out;for(unsigned char c:value){switch(c){case '\\':out<<"\\\\";break;case '"':out<<"\\\"";break;case '\b':out<<"\\b";break;case '\f':out<<"\\f";break;case '\n':out<<"\\n";break;case '\r':out<<"\\r";break;case '\t':out<<"\\t";break;default:if(c<0x20){static constexpr char hex[]="0123456789abcdef";out<<"\\u00"<<hex[(c>>4)&0xf]<<hex[c&0xf];}else out<<static_cast<char>(c);}}return out.str();}
std::string quote(const std::string& value){return "\""+escape(value)+"\"";}
static std::optional<std::size_t> key_value_pos(const std::string& json,const std::string& key){const std::string token="\""+key+"\"";auto p=json.find(token);if(p==std::string::npos)return std::nullopt;p=json.find(':',p+token.size());if(p==std::string::npos)return std::nullopt;++p;while(p<json.size()&&std::isspace(static_cast<unsigned char>(json[p])))++p;return p;}
std::optional<std::string> get_string(const std::string& json,const std::string& key){auto p0=key_value_pos(json,key);if(!p0||*p0>=json.size()||json[*p0]!='"')return std::nullopt;std::size_t p=*p0+1;std::string out;while(p<json.size()){char c=json[p++];if(c=='"')return out;if(c!='\\'){out.push_back(c);continue;}if(p>=json.size())return std::nullopt;char e=json[p++];switch(e){case '"':out.push_back('"');break;case '\\':out.push_back('\\');break;case '/':out.push_back('/');break;case 'b':out.push_back('\b');break;case 'f':out.push_back('\f');break;case 'n':out.push_back('\n');break;case 'r':out.push_back('\r');break;case 't':out.push_back('\t');break;case 'u':if(p+4<=json.size()){out+="\\u";out.append(json,p,4);p+=4;}else return std::nullopt;break;default:return std::nullopt;}}return std::nullopt;}
std::optional<bool> get_bool(const std::string& json,const std::string& key){auto p=key_value_pos(json,key);if(!p)return std::nullopt;if(json.compare(*p,4,"true")==0)return true;if(json.compare(*p,5,"false")==0)return false;return std::nullopt;}
std::string flat_object(const std::initializer_list<std::pair<std::string,std::string>>& string_fields,const std::initializer_list<std::pair<std::string,bool>>& bool_fields){std::string out="{";bool first=true;for(const auto&[k,v]:string_fields){if(!first)out+=',';first=false;out+=quote(k)+":"+quote(v);}for(const auto&[k,v]:bool_fields){if(!first)out+=',';first=false;out+=quote(k)+":"+(v?"true":"false");}out+="}";return out;}
}
