plugins {
    id 'com.android.application'
}

android {
    namespace 'id.airi.os'
    compileSdk 35

    defaultConfig {
        applicationId 'id.airi.os'
        minSdk 23
        targetSdk 35
        versionCode 14
        versionName '14.0.0-hyperflow-edition'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
