package id.airi.eduattend;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.*;

import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class MainActivity extends Activity {
    private static final int REQ_EXPORT_CSV=1001, REQ_BACKUP=1002, REQ_RESTORE=1003;
    private DatabaseHelper db; private LinearLayout content; private long userId=-1; private String displayName="", role="", teacherCode=null; private String pendingCsv="";
    private final int GREEN=Color.rgb(11,107,75), RED=Color.rgb(184,45,45), AMBER=Color.rgb(176,112,0), INK=Color.rgb(25,35,31);
    @Override protected void onCreate(Bundle savedInstanceState){ super.onCreate(savedInstanceState); db=new DatabaseHelper(this); showLogin(); }
    private void showLogin(){ LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(28),dp(60),dp(28),dp(28));root.setBackgroundColor(Color.rgb(250,252,251));root.addView(text("AIRI",14,GREEN,true));root.addView(text("EduAttend",34,INK,true));root.addView(text("Absensi • Kelas • Santri • Honor",15,Color.DKGRAY,false));Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,dp(36)));EditText u=input("Username");EditText p=input("PIN");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);root.addView(u);root.addView(p);Button login=primary("Masuk");login.setOnClickListener(v->{Cursor c=db.login(u.getText().toString().trim(),p.getText().toString());if(c.moveToFirst()){userId=c.getLong(0);displayName=c.getString(2);role=c.getString(3);teacherCode=c.isNull(4)?null:c.getString(4);c.close();db.audit(userId,"LOGIN","role="+role);showDashboard();}else{c.close();toast("Username atau PIN salah");}});root.addView(login);TextView help=text("Akun awal: admin/1234 • piket/1111 • bendahara/2222 • gr001/0000\nGanti PIN setelah login.",12,Color.GRAY,false);help.setPadding(0,dp(20),0,0);root.addView(help);setContentView(root); }
    private void shell(String title){ LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(250,252,251));LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(18),dp(18),dp(18),dp(10));head.addView(text(db.getSetting("institution_name","Sekolah")+" • "+role,12,GREEN,true));head.addView(text(title,25,INK,true));head.addView(text(displayName,12,Color.GRAY,false));root.addView(head);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(8),0,dp(8),dp(6));addNav(nav,"Dashboard",v->showDashboard());addNav(nav,"Guru",v->showTeacherAttendance());addNav(nav,"Kosong",v->showEmptyClasses());addNav(nav,"Santri",v->showStudentClasses());addNav(nav,"Honor",v->showHonor());addNav(nav,"Jadwal",v->showSchedules());if("ADMIN".equals(role)){addNav(nav,"Master",v->showMaster());addNav(nav,"Audit",v->showAudit());}addNav(nav,"Setelan",v->showSettings());hs.addView(nav);root.addView(hs);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(13),dp(6),dp(13),dp(32));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root); }
    private void showDashboard(){ shell("Dashboard Hari Ini");LinearLayout a=new LinearLayout(this);a.addView(stat("Jadwal",String.valueOf(db.getScheduledCount(role,teacherCode)),GREEN),weight());a.addView(stat("Hadir",String.valueOf(db.getPresentTeacherCount(role,teacherCode)),GREEN),weight());content.addView(a);LinearLayout b=new LinearLayout(this);b.addView(stat("Kelas Kosong",String.valueOf(db.getEmptyClassCount()),RED),weight());b.addView(stat("Santri Absen",String.valueOf(db.getAbsentStudentCount()),AMBER),weight());content.addView(b);LinearLayout h=card();h.addView(text("Honor bulan "+db.currentMonth(),13,Color.DKGRAY,false));long total=0;Cursor c=db.getHonorRecap(role,teacherCode);while(c.moveToNext())total+=db.honorForMinutes(c.getInt(3));c.close();h.addView(text(rupiah(total),29,GREEN,true));h.addView(text("Tarif "+rupiah(db.getIntSetting("honor_per_hour",15000))+" / jam",12,Color.GRAY,false));content.addView(h);content.addView(title("Status Sistem"));content.addView(info("Deteksi kelas kosong aktif dengan toleransi "+db.getIntSetting("late_tolerance_minutes",15)+" menit."));content.addView(info("Semua perubahan penting dicatat di Audit Log."));content.addView(info("Data tersimpan offline di perangkat dan dapat dibackup manual.")); }
    private void showTeacherAttendance(){ shell("Absensi Mengajar Guru");content.addView(info("Jadwal adalah sumber utama. Status HADIR dihitung ke honor; Izin/Sakit/Tidak Hadir tidak dihitung."));Cursor c=db.getTodaySchedules(role,teacherCode);if(c.getCount()==0)content.addView(empty("Tidak ada jadwal hari ini."));while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));String status=c.getString(c.getColumnIndexOrThrow("attendance_status"));LinearLayout row=card();row.addView(text(c.getString(c.getColumnIndexOrThrow("start_time"))+"–"+c.getString(c.getColumnIndexOrThrow("end_time"))+" • "+c.getString(c.getColumnIndexOrThrow("class_code")),13,GREEN,true));row.addView(text(c.getString(c.getColumnIndexOrThrow("teacher_name")),18,INK,true));row.addView(text(c.getString(c.getColumnIndexOrThrow("subject_name")),14,Color.DKGRAY,false));row.addView(text(status+(("HADIR".equals(status)&&c.getInt(c.getColumnIndexOrThrow("late_minutes"))>0)?" • telat "+c.getInt(c.getColumnIndexOrThrow("late_minutes"))+" mnt":""),12,"HADIR".equals(status)?GREEN:("BELUM ABSEN".equals(status)?RED:AMBER),true));row.setOnClickListener(v->chooseTeacherStatus(id));content.addView(row);}c.close(); }
    private void chooseTeacherStatus(long scheduleId){ if("BENDAHARA".equals(role)){toast("Bendahara hanya dapat melihat honor.");return;}String[] items={"HADIR","IZIN","SAKIT","TIDAK HADIR"};new AlertDialog.Builder(this).setTitle("Status Mengajar").setItems(items,(d,w)->askNote("Catatan (opsional)",note->{db.markTeacherAttendance(userId,scheduleId,items[w],note);showTeacherAttendance();})).show(); }
    private void showEmptyClasses(){ shell("Monitoring Kelas Kosong");int tol=db.getIntSetting("late_tolerance_minutes",15),now=db.currentMinutes(),shown=0;Cursor c=db.getTodaySchedules("ADMIN",null);while(c.moveToNext()){String start=c.getString(c.getColumnIndexOrThrow("start_time"));String status=c.getString(c.getColumnIndexOrThrow("attendance_status"));if(now>db.toMinutes(start)+tol&&!"HADIR".equals(status)){shown++;long id=c.getLong(c.getColumnIndexOrThrow("id"));LinearLayout row=card();row.addView(text("KELAS KOSONG",12,RED,true));row.addView(text(c.getString(c.getColumnIndexOrThrow("class_code"))+" • "+c.getString(c.getColumnIndexOrThrow("subject_name")),18,INK,true));row.addView(text(c.getString(c.getColumnIndexOrThrow("teacher_name"))+" • "+start+"–"+c.getString(c.getColumnIndexOrThrow("end_time")),13,Color.DKGRAY,false));row.addView(text("Status: "+status,12,RED,true));if(!"BENDAHARA".equals(role))row.setOnClickListener(v->chooseTeacherStatus(id));content.addView(row);}}c.close();if(shown==0)content.addView(empty("Tidak ada kelas kosong terdeteksi.")); }
    private void showStudentClasses(){ shell("Absensi Santri");if("BENDAHARA".equals(role)){content.addView(empty("Menu absensi santri tidak tersedia untuk Bendahara."));return;}Cursor c=db.getClasses();while(c.moveToNext()){String code=c.getString(0),name=c.getString(1);LinearLayout row=card();row.addView(text(code,12,GREEN,true));row.addView(text(name,18,INK,true));row.addView(text("Buka daftar santri →",12,Color.GRAY,false));row.setOnClickListener(v->showStudents(code,name));content.addView(row);}c.close(); }
    private void showStudents(String cls,String clsName){ shell("Santri • "+clsName);Cursor c=db.getStudents(cls);while(c.moveToNext()){long id=c.getLong(0);String status=c.getString(3);LinearLayout row=card();row.addView(text(c.getString(2),17,INK,true));row.addView(text("NIS "+c.getString(1),12,Color.GRAY,false));row.addView(text(status,12,"HADIR".equals(status)?GREEN:("BELUM".equals(status)?Color.GRAY:RED),true));row.setOnClickListener(v->chooseStudentStatus(id,cls,clsName));content.addView(row);}c.close(); }
    private void chooseStudentStatus(long id,String cls,String clsName){String[] items={"HADIR","IZIN","SAKIT","ALPHA"};new AlertDialog.Builder(this).setTitle("Status Santri").setItems(items,(d,w)->askNote("Catatan (opsional)",note->{db.markStudentAttendance(userId,id,items[w],note);showStudents(cls,clsName);})).show(); }
    private void showHonor(){ shell("Honor Mengajar • "+db.currentMonth());Cursor c=db.getHonorRecap(role,teacherCode);while(c.moveToNext()){int mins=c.getInt(3);LinearLayout row=card();row.addView(text(c.getString(1),18,INK,true));row.addView(text(c.getString(0)+" • "+c.getInt(2)+" sesi • "+String.format(Locale.getDefault(),"%.2f jam",mins/60.0),13,Color.DKGRAY,false));row.addView(text(rupiah(db.honorForMinutes(mins)),21,GREEN,true));content.addView(row);}c.close();if(!"GURU".equals(role)){Button e=primary("Ekspor Rekap CSV");e.setOnClickListener(v->exportCsv());content.addView(e);} }
    private void showSchedules(){ shell("Jadwal Mengajar");Cursor c=db.getAllSchedules();while(c.moveToNext()){LinearLayout row=card();row.addView(text(dayName(c.getInt(1))+" • "+c.getString(2)+"–"+c.getString(3),13,GREEN,true));row.addView(text(c.getString(4)+" • "+c.getString(5),17,INK,true));row.addView(text(c.getString(6),13,Color.DKGRAY,false));content.addView(row);}c.close();if("ADMIN".equals(role)){Button add=primary("Tambah Jadwal");add.setOnClickListener(v->addScheduleDialog());content.addView(add);} }
    private void showMaster(){ shell("Master Data");content.addView(title("Guru"));renderSimple(db.getTeachers(),1,0);Button gt=secondary("+ Guru");gt.setOnClickListener(v->twoFieldDialog("Tambah Guru","Kode","Nama",(a,b)->{try{db.addTeacher(userId,a,b);showMaster();}catch(Exception e){toast("Gagal: "+e.getMessage());}}));content.addView(gt);content.addView(title("Kelas"));renderSimple(db.getClasses(),1,0);Button cl=secondary("+ Kelas");cl.setOnClickListener(v->twoFieldDialog("Tambah Kelas","Kode","Nama",(a,b)->{try{db.addClass(userId,a,b);showMaster();}catch(Exception e){toast("Gagal: "+e.getMessage());}}));content.addView(cl);content.addView(title("Mata Pelajaran"));renderSimple(db.getSubjects(),1,0);Button sb=secondary("+ Mapel");sb.setOnClickListener(v->twoFieldDialog("Tambah Mapel","Kode","Nama",(a,b)->{try{db.addSubject(userId,a,b);showMaster();}catch(Exception e){toast("Gagal: "+e.getMessage());}}));content.addView(sb);content.addView(title("Tambah Santri"));Button st=secondary("+ Santri");st.setOnClickListener(v->addStudentDialog());content.addView(st); }
    private void renderSimple(Cursor c,int nameCol,int codeCol){while(c.moveToNext()){LinearLayout r=card();r.addView(text(c.getString(nameCol),16,INK,true));r.addView(text(c.getString(codeCol),12,Color.GRAY,false));content.addView(r);}c.close();}
    private void showAudit(){ shell("Audit Log");Cursor c=db.getAudit();while(c.moveToNext()){LinearLayout r=card();r.addView(text(c.getString(2),13,GREEN,true));r.addView(text(c.getString(1)+" • "+c.getString(0),12,Color.GRAY,false));r.addView(text(c.getString(3),13,Color.DKGRAY,false));content.addView(r);}c.close(); }
    private void showSettings(){ shell("Setelan");content.addView(info("Aplikasi offline-first. Backup database secara berkala dan jangan gunakan PIN awal untuk operasional tetap."));if("ADMIN".equals(role)){Button inst=secondary("Nama Lembaga: "+db.getSetting("institution_name","Sekolah"));inst.setOnClickListener(v->singleSetting("institution_name","Nama lembaga",false));content.addView(inst);Button rate=secondary("Honor/Jam: "+rupiah(db.getIntSetting("honor_per_hour",15000)));rate.setOnClickListener(v->singleSetting("honor_per_hour","Honor per jam",true));content.addView(rate);Button tol=secondary("Toleransi: "+db.getIntSetting("late_tolerance_minutes",15)+" menit");tol.setOnClickListener(v->singleSetting("late_tolerance_minutes","Toleransi terlambat (menit)",true));content.addView(tol);Button bk=secondary("Backup Database");bk.setOnClickListener(v->backupDb());content.addView(bk);Button rs=secondary("Restore Database");rs.setOnClickListener(v->restoreDb());content.addView(rs);}Button pin=secondary("Ganti PIN Saya");pin.setOnClickListener(v->changePin());content.addView(pin);Button out=primary("Keluar");out.setOnClickListener(v->{db.audit(userId,"LOGOUT","");userId=-1;role="";teacherCode=null;showLogin();});content.addView(out); }
    private void exportCsv(){pendingCsv=db.buildHonorCsv(role,teacherCode);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"honor-"+db.currentMonth()+".csv");startActivityForResult(i,REQ_EXPORT_CSV);}
    private void backupDb(){db.close();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/octet-stream");i.putExtra(Intent.EXTRA_TITLE,"airi-eduattend-backup.db");startActivityForResult(i,REQ_BACKUP);}
    private void restoreDb(){db.close();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/octet-stream");startActivityForResult(i,REQ_RESTORE);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data==null||data.getData()==null){db=new DatabaseHelper(this);return;}Uri uri=data.getData();try{if(req==REQ_EXPORT_CSV){try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(pendingCsv.getBytes(StandardCharsets.UTF_8));}toast("CSV berhasil disimpan");}else if(req==REQ_BACKUP){BackupUtil.exportDb(this,uri);toast("Backup berhasil");}else if(req==REQ_RESTORE){BackupUtil.importDb(this,uri);toast("Restore berhasil. Silakan login ulang.");}}catch(Exception e){toast("Gagal: "+e.getMessage());}db=new DatabaseHelper(this);if(req==REQ_RESTORE)showLogin();}
    private void addStudentDialog(){Cursor c=db.getClasses();List<String> codes=new ArrayList<>();while(c.moveToNext())codes.add(c.getString(0));c.close();if(codes.isEmpty()){toast("Tambah kelas terlebih dahulu");return;}LinearLayout box=dialogBox();EditText nis=input("NIS");EditText name=input("Nama santri");Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,codes));box.addView(nis);box.addView(name);box.addView(sp);new AlertDialog.Builder(this).setTitle("Tambah Santri").setView(box).setPositiveButton("Simpan",(d,w)->{try{db.addStudent(userId,nis.getText().toString(),name.getText().toString(),codes.get(sp.getSelectedItemPosition()));showMaster();}catch(Exception e){toast("Gagal: "+e.getMessage());}}).setNegativeButton("Batal",null).show();}
    private void addScheduleDialog(){List<String> teachers=col(db.getTeachers(),0),classes=col(db.getClasses(),0),subjects=col(db.getSubjects(),0);if(teachers.isEmpty()||classes.isEmpty()||subjects.isEmpty()){toast("Lengkapi master data terlebih dahulu");return;}LinearLayout box=dialogBox();Spinner day=spinner(new String[]{"Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"});Spinner t=spinner(teachers.toArray(new String[0])),cl=spinner(classes.toArray(new String[0])),su=spinner(subjects.toArray(new String[0]));EditText st=input("Jam mulai HH:mm"),en=input("Jam selesai HH:mm");box.addView(day);box.addView(t);box.addView(cl);box.addView(su);box.addView(st);box.addView(en);new AlertDialog.Builder(this).setTitle("Tambah Jadwal").setView(box).setPositiveButton("Simpan",(d,w)->{String a=st.getText().toString().trim(),b=en.getText().toString().trim();if(!validTime(a)||!validTime(b)){toast("Format jam harus HH:mm");return;}try{db.addSchedule(userId,day.getSelectedItemPosition()+1,teachers.get(t.getSelectedItemPosition()),classes.get(cl.getSelectedItemPosition()),subjects.get(su.getSelectedItemPosition()),a,b);showSchedules();}catch(Exception e){toast("Gagal: "+e.getMessage());}}).setNegativeButton("Batal",null).show();}
    private List<String> col(Cursor c,int ix){List<String> l=new ArrayList<>();while(c.moveToNext())l.add(c.getString(ix));c.close();return l;}
    private Spinner spinner(String[] values){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));return s;}
    private boolean validTime(String s){return s.matches("([01]\\d|2[0-3]):[0-5]\\d");}
    private void singleSetting(String key,String title,boolean number){EditText e=input(title);e.setText(db.getSetting(key,""));if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Simpan",(d,w)->{db.setSetting(userId,key,e.getText().toString().trim());showSettings();}).setNegativeButton("Batal",null).show();}
    private void changePin(){EditText e=input("PIN baru minimal 4 digit");e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Ganti PIN").setView(e).setPositiveButton("Simpan",(d,w)->{String p=e.getText().toString();if(p.length()<4){toast("PIN minimal 4 digit");return;}db.changePin(userId,p);toast("PIN diperbarui");}).setNegativeButton("Batal",null).show();}
    interface NoteCallback{void run(String s);}private void askNote(String title,NoteCallback cb){EditText e=input(title);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Simpan",(d,w)->cb.run(e.getText().toString().trim())).setNegativeButton("Batal",null).show();}
    interface TwoCallback{void run(String a,String b);}private void twoFieldDialog(String title,String h1,String h2,TwoCallback cb){LinearLayout box=dialogBox();EditText a=input(h1),b=input(h2);box.addView(a);box.addView(b);new AlertDialog.Builder(this).setTitle(title).setView(box).setPositiveButton("Simpan",(d,w)->cb.run(a.getText().toString(),b.getText().toString())).setNegativeButton("Batal",null).show();}
    private LinearLayout dialogBox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(20),dp(8),dp(20),0);return l;}
    private void addNav(LinearLayout nav,String label,View.OnClickListener l){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(11);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(42));p.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(p);nav.addView(b);}
    private LinearLayout stat(String label,String val,int color){LinearLayout c=card();c.addView(text(label,12,Color.DKGRAY,false));c.addView(text(val,28,color,true));return c;}
    private LinearLayout card(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(15),dp(13),dp(15),dp(13));b.setBackgroundColor(Color.WHITE);b.setElevation(dp(1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(4),dp(4),dp(4),dp(4));b.setLayoutParams(p);return b;}
    private TextView text(String s,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);v.setPadding(0,dp(2),0,dp(2));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private TextView title(String s){TextView v=text(s,18,INK,true);v.setPadding(dp(4),dp(18),dp(4),dp(6));return v;}
    private TextView info(String s){TextView v=text(s,13,Color.DKGRAY,false);v.setBackgroundColor(Color.rgb(235,246,240));v.setPadding(dp(13),dp(11),dp(13),dp(11));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(4),dp(4),dp(4),dp(4));v.setLayoutParams(p);return v;}
    private TextView empty(String s){TextView v=text(s,15,Color.GRAY,false);v.setGravity(Gravity.CENTER);v.setPadding(dp(10),dp(45),dp(10),dp(45));return v;}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(4),0,dp(4));e.setLayoutParams(p);return e;}
    private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(GREEN);b.setAllCaps(false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(dp(4),dp(8),dp(4),dp(4));b.setLayoutParams(p);return b;}
    private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(dp(4),dp(4),dp(4),dp(4));b.setLayoutParams(p);return b;}
    private LinearLayout.LayoutParams weight(){return new LinearLayout.LayoutParams(0,-2,1);}
    private String rupiah(long n){NumberFormat nf=NumberFormat.getCurrencyInstance(new Locale("id","ID"));nf.setMaximumFractionDigits(0);return nf.format(n);}
    private String dayName(int d){String[] a={"","Minggu","Senin","Selasa","Rabu","Kamis","Jumat","Sabtu"};return d>=1&&d<=7?a[d]:"?";}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
}
