package com.airi.litesystem;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Environment;
import android.os.Handler;
import android.os.Looper;
import android.os.StatFs;
import android.provider.Settings;
import android.view.Gravity;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import java.io.*;
import java.util.*;

public class StorageActivity extends Activity {
    private TextView internalInfo,sdInfo,scanInfo,progressText; private ProgressBar progress; private File sdRoot; private final Handler main=new Handler(Looper.getMainLooper()); private volatile boolean busy=false; private final LinkedHashMap<String,File> categories=new LinkedHashMap<>();
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Ui.BG);getWindow().setNavigationBarColor(Ui.BG);setupCategories();setContentView(build());refresh();}
    @Override protected void onResume(){super.onResume();refresh();}
    private void setupCategories(){File ext=Environment.getExternalStorageDirectory();categories.put("Foto Kamera",new File(ext,"DCIM"));categories.put("Gambar",new File(ext,"Pictures"));categories.put("Video",new File(ext,"Movies"));categories.put("Download",new File(ext,"Download"));categories.put("Dokumen",new File(ext,"Documents"));categories.put("Musik",new File(ext,"Music"));categories.put("WhatsApp Media",new File(ext,"Android/media/com.whatsapp/WhatsApp/Media"));}
    private ScrollView build(){ScrollView s=new ScrollView(this);s.setBackgroundColor(Ui.BG);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(Ui.dp(this,20),Ui.dp(this,18),Ui.dp(this,20),Ui.dp(this,28));s.addView(r);r.addView(Ui.text(this,"AIRI SD Mover",30,Ui.TEXT));r.addView(Ui.text(this,"Pindahkan file besar tanpa root",15,Ui.MUTED));LinearLayout card=Ui.card(this);r.addView(card,Ui.lpMatch(-2,this));Ui.setMargins(card,0,18,0,0,this);internalInfo=Ui.text(this,"Internal: memeriksa…",16,Ui.TEXT);card.addView(internalInfo);sdInfo=Ui.text(this,"SD Card: memeriksa…",16,Ui.TEXT);card.addView(sdInfo);Ui.setMargins(sdInfo,0,8,0,0,this);TextView perm=Ui.button(this,"Izinkan kelola semua file");perm.setOnClickListener(v->requestAllFiles());r.addView(perm,Ui.lpMatch(52,this));Ui.setMargins(perm,0,16,0,0,this);TextView scan=Ui.button(this,"Scan file yang bisa dipindahkan");scan.setOnClickListener(v->scan());r.addView(scan,Ui.lpMatch(52,this));Ui.setMargins(scan,0,10,0,0,this);scanInfo=Ui.text(this,"Belum discan.",14,Ui.MUTED);r.addView(scanInfo);Ui.setMargins(scanInfo,2,12,2,0,this);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);r.addView(progress,new LinearLayout.LayoutParams(-1,Ui.dp(this,8)));Ui.setMargins(progress,0,16,0,0,this);progressText=Ui.text(this,"",13,Ui.MUTED);progressText.setGravity(Gravity.CENTER);r.addView(progressText);for(String k:categories.keySet()){TextView x=Ui.button(this,"Pindahkan "+k+" → SD");x.setOnClickListener(v->moveCategory(k));r.addView(x,Ui.lpMatch(50,this));Ui.setMargins(x,0,10,0,0,this);}TextView warning=Ui.text(this,"AIRI tidak menyentuh /Android/data, data privat aplikasi, atau file sistem. File sumber hanya dihapus setelah salinan tujuan terverifikasi.",13,Ui.MUTED);warning.setPadding(0,Ui.dp(this,18),0,0);r.addView(warning);return s;}
    private void requestAllFiles(){if(Build.VERSION.SDK_INT>=30){try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}}
    private boolean hasAllFiles(){return Build.VERSION.SDK_INT<30||Environment.isExternalStorageManager();}
    private void refresh(){if(internalInfo==null||sdInfo==null)return;internalInfo.setText("Internal: "+stat(Environment.getExternalStorageDirectory()));sdRoot=findSdRoot();sdInfo.setText(sdRoot==null?"SD Card: tidak terdeteksi":"SD Card: "+stat(sdRoot));}
    private String stat(File f){try{StatFs s=new StatFs(f.getAbsolutePath());long total=s.getTotalBytes(),free=s.getAvailableBytes();return human(total-free)+" / "+human(total)+" • kosong "+human(free);}catch(Exception e){return "tidak tersedia";}}
    private File findSdRoot(){File[] dirs=getExternalFilesDirs(null);if(dirs==null)return null;for(File d:dirs){if(d==null)continue;try{if(Environment.isExternalStorageRemovable(d)){String p=d.getAbsolutePath();int i=p.indexOf("/Android/data/");return i>0?new File(p.substring(0,i)):d;}}catch(Exception ignored){}}return null;}
    private void scan(){if(busy)return;if(!hasAllFiles()){toast("Aktifkan izin kelola semua file terlebih dahulu.");requestAllFiles();return;}busy=true;scanInfo.setText("Memindai…");new Thread(()->{long total=0;StringBuilder sb=new StringBuilder();for(Map.Entry<String,File> e:categories.entrySet()){long sz=sizeOf(e.getValue());total+=sz;sb.append(e.getKey()).append(": ").append(human(sz)).append("\n");}long finalTotal=total;main.post(()->{scanInfo.setText(sb+"\nTotal kandidat: "+human(finalTotal));busy=false;});}).start();}
    private void moveCategory(String name){if(busy){toast("Masih ada proses berjalan.");return;}if(!hasAllFiles()){toast("Aktifkan izin kelola semua file dahulu.");requestAllFiles();return;}sdRoot=findSdRoot();if(sdRoot==null){toast("SD Card tidak terdeteksi.");return;}File src=categories.get(name);if(src==null||!src.exists()){toast("Folder sumber tidak ditemukan.");return;}File dst=new File(sdRoot,"AIRI_Data/"+safe(name));if(!dst.exists()&&!dst.mkdirs()){toast("Gagal membuat folder tujuan di SD.");return;}ArrayList<File> files=new ArrayList<>();collect(src,files);if(files.isEmpty()){toast("Tidak ada file untuk dipindahkan.");return;}busy=true;progress.setProgress(0);progressText.setText("Menyiapkan…");new Thread(()->{int done=0,ok=0,fail=0;long moved=0;for(File f:files){try{File rel=relative(src,f,dst);if(copyVerifyDelete(f,rel)){ok++;moved+=rel.length();}else fail++;}catch(Exception e){fail++;}done++;int pct=(int)((done*100L)/files.size());int d=done,o=ok,fa=fail;long mv=moved;main.post(()->{progress.setProgress(pct);progressText.setText(d+" / "+files.size()+" • berhasil "+o+" • gagal "+fa+" • "+human(mv));});}cleanupEmpty(src);int o=ok,fa=fail;long mv=moved;main.post(()->{busy=false;refresh();scanInfo.setText("Selesai "+name+": "+o+" file, "+human(mv)+" dipindahkan. Gagal: "+fa);toast("Pemindahan selesai.");});}).start();}
    private static File relative(File root,File src,File dstRoot)throws IOException{String rp=root.getCanonicalPath(),sp=src.getCanonicalPath();String rel=sp.startsWith(rp)?sp.substring(rp.length()):src.getName();while(rel.startsWith(File.separator))rel=rel.substring(1);File out=new File(dstRoot,rel);File p=out.getParentFile();if(p!=null&&!p.exists())p.mkdirs();if(out.exists()){String n=out.getName();int dot=n.lastIndexOf('.');String base=dot>0?n.substring(0,dot):n,ext=dot>0?n.substring(dot):"";out=new File(out.getParentFile(),base+"_"+System.currentTimeMillis()+ext);}return out;}
    private static boolean copyVerifyDelete(File src,File dst){long expected=src.length();try(InputStream in=new BufferedInputStream(new FileInputStream(src));OutputStream out=new BufferedOutputStream(new FileOutputStream(dst))){byte[] buf=new byte[1024*1024];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);out.flush();}catch(Exception e){dst.delete();return false;}if(!dst.exists()||dst.length()!=expected){dst.delete();return false;}dst.setLastModified(src.lastModified());return src.delete();}
    private static void collect(File f,List<File> out){if(f==null||!f.exists())return;if(f.isFile()){out.add(f);return;}File[] xs=f.listFiles();if(xs==null)return;for(File x:xs){String p=x.getAbsolutePath();if(p.contains("/Android/data/")||p.contains("/Android/obb/"))continue;collect(x,out);}}
    private static void cleanupEmpty(File d){if(d==null||!d.isDirectory())return;File[] xs=d.listFiles();if(xs!=null)for(File x:xs)if(x.isDirectory())cleanupEmpty(x);xs=d.listFiles();if(xs!=null&&xs.length==0)d.delete();}
    private static long sizeOf(File f){if(f==null||!f.exists())return 0;if(f.isFile())return f.length();long s=0;File[] xs=f.listFiles();if(xs!=null)for(File x:xs)s+=sizeOf(x);return s;}
    private static String safe(String s){return s.replaceAll("[^a-zA-Z0-9._-]","_");}
    private static String human(long b){String[] u={"B","KB","MB","GB","TB"};double v=b;int i=0;while(v>=1024&&i<u.length-1){v/=1024;i++;}return String.format(Locale.US,i==0?"%.0f %s":"%.1f %s",v,u[i]);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
