const HOST='com.airi.downloadmanager';const handled=new Set();
async function cfg(){return chrome.storage.local.get({monitorAllDownloads:true});}
async function cookieHeader(url){try{return (await chrome.cookies.getAll({url})).map(c=>`${c.name}=${c.value}`).join('; ')}catch{return ''}}
function nativeSend(payload){return new Promise(resolve=>chrome.runtime.sendNativeMessage(HOST,payload,response=>{const e=chrome.runtime.lastError;resolve({ok:!e&&!!response?.ok,response,error:e?.message||response?.message||''})}))}
async function handoff(item){if(!item||handled.has(item.id))return;handled.add(item.id);if(!(await cfg()).monitorAllDownloads)return;const url=item.finalUrl||item.url||'';if(!/^https?:\/\//i.test(url))return;try{await chrome.downloads.pause(item.id)}catch{}const result=await nativeSend({action:'download',url,filename:item.filename?item.filename.split(/[\\/]/).pop():'',referer:item.referrer||'',cookie:await cookieHeader(url),userAgent:navigator.userAgent||'',source:'browser-download',mime:item.mime||''});if(result.ok){try{await chrome.downloads.cancel(item.id)}catch{}try{await chrome.downloads.erase({id:item.id})}catch{}}else{try{await chrome.downloads.resume(item.id)}catch{}await chrome.storage.local.set({lastBridgeError:result.error||'Desktop rejected request'})}}
chrome.downloads.onCreated.addListener(handoff);
chrome.runtime.onInstalled.addListener(()=>{chrome.storage.local.get({monitorAllDownloads:true},v=>chrome.storage.local.set(v));chrome.contextMenus.create({id:'airi-download-link',title:'Download with AIRI Download Manager',contexts:['link']});chrome.contextMenus.create({id:'airi-download-page',title:'Download page media with AIRI',contexts:['page']});});
chrome.contextMenus.onClicked.addListener(async(info,tab)=>{if(info.menuItemId==='airi-download-link'&&info.linkUrl)await nativeSend({action:'download',url:info.linkUrl,filename:'',referer:tab?.url||'',cookie:await cookieHeader(info.linkUrl),userAgent:navigator.userAgent||'',source:'context-menu'});if(info.menuItemId==='airi-download-page'&&tab?.url)await nativeSend({action:'media_page',pageUrl:tab.url,title:tab.title||'Media',quality:'best',cookie:await cookieHeader(tab.url),referer:tab.url,userAgent:navigator.userAgent||'',source:'context-menu'});});
chrome.runtime.onMessage.addListener((m,s,send)=>{if(m?.type==='airi-media-page'){(async()=>{const pageUrl=m.pageUrl||s.tab?.url||'';send(await nativeSend({action:'media_page',pageUrl,title:m.title||s.tab?.title||'Media',quality:m.quality||'best',cookie:await cookieHeader(pageUrl),referer:pageUrl,userAgent:navigator.userAgent||'',source:'youtube-overlay'}))})();return true;}if(m?.type==='airi-bridge-ping'){nativeSend({action:'ping'}).then(send);return true;}});
