(()=>{
  if(window.__AIRI_UNIVERSAL_MEDIA_36)return;
  window.__AIRI_UNIVERSAL_MEDIA_36=true;
  const mounted=new WeakMap();
  const MIN_W=240,MIN_H=135;
  let enabled=true,lastConfigCheck=0;

  async function refreshConfig(force=false){if(!force&&Date.now()-lastConfigCheck<5000)return enabled;lastConfigCheck=Date.now();try{const r=await chrome.runtime.sendMessage({type:'airi-config-for-page',url:location.href});enabled=!!(r?.overlayEnabled&&r?.siteEnabled)}catch{enabled=false}if(!enabled){document.querySelectorAll('.airi-universal-wrap').forEach(x=>x.style.display='none')}return enabled}
  function eligible(el){const r=el.getBoundingClientRect();return r.width>=MIN_W&&r.height>=MIN_H&&r.bottom>0&&r.right>0}
  async function sendMedia(el,button){if(!(await refreshConfig(true)))return;const old=button.textContent;button.disabled=true;button.textContent='AIRI: detecting...';const direct=[];const push=u=>{try{if(u&&/^https?:\/\//i.test(u)&&!direct.includes(u))direct.push(u)}catch{}};push(el.currentSrc);push(el.src);el.querySelectorAll?.('source[src]').forEach(s=>push(s.src));const response=await chrome.runtime.sendMessage({type:'airi-universal-media',pageUrl:location.href,title:document.title||'Media',directUrls:direct,mediaType:el.tagName.toLowerCase()});button.textContent=response?.ok?'Started in AIRI':'AIRI: '+String(response?.error||response?.response?.message||'failed').slice(0,36);setTimeout(()=>{button.textContent=old;button.disabled=false},2400)}
  async function mount(el){if(mounted.has(el)||!eligible(el)||!(await refreshConfig()))return;const wrap=document.createElement('div');wrap.className='airi-universal-wrap';const btn=document.createElement('button');btn.className='airi-universal-btn';btn.textContent='AIRI DM';btn.title='Download this media with AIRI Download Manager';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();sendMedia(el,btn)});wrap.appendChild(btn);document.documentElement.appendChild(wrap);mounted.set(el,wrap);const place=()=>{if(!el.isConnected){wrap.remove();return}const r=el.getBoundingClientRect();if(!enabled||!eligible(el)){wrap.style.display='none';return}wrap.style.display='block';wrap.style.left=Math.max(8,r.right-126)+'px';wrap.style.top=Math.max(8,r.top+12)+'px'};place();const ro=new ResizeObserver(place);ro.observe(el);const iv=setInterval(async()=>{if(!el.isConnected){clearInterval(iv);ro.disconnect();wrap.remove()}else{await refreshConfig();place()}},1000)}
  function scan(){if(!enabled)return;document.querySelectorAll('video,audio').forEach(mount)}
  const mo=new MutationObserver(scan);mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['src']});window.addEventListener('scroll',scan,{passive:true});window.addEventListener('resize',scan,{passive:true});setInterval(async()=>{await refreshConfig();scan()},1800);refreshConfig(true).then(scan);
})();
