package com.airi.sdmover;
import android.app.*; import android.os.*; import android.content.*; import android.content.pm.*; import android.graphics.Color; import android.graphics.Typeface; import android.provider.Settings; import android.view.*; import android.widget.*; import java.util.*; import java.util.concurrent.*;
public class MainActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor(); private LinearLayout root,appsContainer; private TextView status,volumeInfo,log; private String diskId,volumeUuid; private List<AppEntry> apps=new ArrayList<>();
 @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();refreshAll();}
 private TextView text(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(27,34,48));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setPadding(0,6,0,6);return v;}
 private Button button(String l){Button b=new Button(this);b.setText(l);b.setAllCaps(false);return b;}
 private void buildUi(){ScrollView scroll=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(32,32,32,40);scroll.addView(root);setContentView(scroll);root.addView(text("AIRI SD Mover",28,true));root.addView(text("Realme 3 Pro • Root Storage Utility",14,false));TextView warn=text("⚠ Adoptable Storage dapat memformat/menghapus isi SD card. Backup dulu.",14,true);warn.setTextColor(Color.rgb(177,65,35));root.addView(warn);status=text("Memeriksa ROOT…",16,true);root.addView(status);volumeInfo=text("Storage: memeriksa…",14,false);root.addView(volumeInfo);LinearLayout row=new LinearLayout(this);Button refresh=button("Refresh");refresh.setOnClickListener(v->refreshAll());row.addView(refresh);Button settingsBtn=button("App Settings");settingsBtn.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+getPackageName()))));row.addView(settingsBtn);root.addView(row);root.addView(text("1. Persiapan SD",20,true));Button force=button("Aktifkan Force-Adoptable");force.setOnClickListener(v->confirmForceAdopt());root.addView(force);Button format=button("FORMAT SD → Internal/Adoptable");format.setOnClickListener(v->confirmFormat());root.addView(format);root.addView(text("2. Aplikasi",20,true));appsContainer=new LinearLayout(this);appsContainer.setOrientation(LinearLayout.VERTICAL);root.addView(appsContainer);root.addView(text("Log",18,true));log=text("",12,false);log.setTextIsSelectable(true);root.addView(log);}
 private void appendLog(String s){runOnUiThread(()->log.append((log.length()==0?"":"\n")+s));}
 private void refreshAll(){status.setText("Memeriksa ROOT…");volumeInfo.setText("Storage: memeriksa…");appsContainer.removeAllViews();worker.submit(()->{boolean rootOk=RootShell.hasRoot();if(!rootOk){runOnUiThread(()->{status.setText("ROOT: TIDAK TERSEDIA");volumeInfo.setText("Magisk/su diperlukan untuk mode paksa.");});loadApps();return;}runOnUiThread(()->status.setText("ROOT: AKTIF ✓"));try{RootShell.Result d=RootShell.run("sm list-disks");diskId=parseFirstDisk(d.out);RootShell.Result vols=RootShell.run("sm list-volumes all");volumeUuid=parsePrivateUuid(vols.out);String info="Disk SD: "+(diskId==null?"tidak terdeteksi":diskId)+"\nPrivate volume: "+(volumeUuid==null?"belum ada":volumeUuid);runOnUiThread(()->volumeInfo.setText(info));appendLog("sm list-disks → "+d.combined());appendLog("sm list-volumes all → "+vols.combined());}catch(Exception e){appendLog("ERROR storage: "+e);}loadApps();});}
 private String parseFirstDisk(String out){if(out==null)return null;for(String line:out.split("\\r?\\n")){line=line.trim();if(line.startsWith("disk:"))return line.split("\\s+")[0];}return null;}
 private String parsePrivateUuid(String out){if(out==null)return null;for(String line:out.split("\\r?\\n")){line=line.trim();if(line.startsWith("private")&&line.contains(" mounted ")){String[] p=line.split("\\s+");for(int i=p.length-1;i>=0;i--){String x=p[i];if(x.matches("[0-9a-fA-F-]{8,}")&&!x.contains(","))return x;}}}return null;}
 private void loadApps(){PackageManager pm=getPackageManager();List<AppEntry> tmp=new ArrayList<>();for(ApplicationInfo ai:pm.getInstalledApplications(0)){if((ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0||ai.packageName.equals(getPackageName()))continue;tmp.add(new AppEntry(String.valueOf(pm.getApplicationLabel(ai)),ai.packageName,ai.sourceDir,pm.getApplicationIcon(ai)));}Collections.sort(tmp,(a,b)->a.label.compareToIgnoreCase(b.label));apps=tmp;runOnUiThread(this::renderApps);}
 private void renderApps(){appsContainer.removeAllViews();for(AppEntry a:apps){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(18,16,18,16);card.addView(text(a.label+(a.onAdoptedStorage()?"  • SD":"  • Internal"),16,true));card.addView(text(a.packageName,11,false));LinearLayout r=new LinearLayout(this);Button toSd=button("→ SD");toSd.setEnabled(volumeUuid!=null);toSd.setOnClickListener(v->moveApp(a,true));r.addView(toSd);Button toInt=button("→ Internal");toInt.setOnClickListener(v->moveApp(a,false));r.addView(toInt);card.addView(r);appsContainer.addView(card);}}
 private void confirmForceAdopt(){new AlertDialog.Builder(this).setTitle("Force Adoptable Storage").setMessage("Mengaktifkan dukungan adoptable storage.").setNegativeButton("Batal",null).setPositiveButton("Aktifkan",(d,w)->runRoot("sm set-force-adoptable true",true)).show();}
 private void confirmFormat(){if(diskId==null){toast("SD card tidak terdeteksi.");return;}new AlertDialog.Builder(this).setTitle("HAPUS & FORMAT SD CARD?").setMessage("SEMUA DATA pada SD card "+diskId+" akan DIHAPUS.").setNegativeButton("BATAL",null).setPositiveButton("SAYA PAHAM, FORMAT",(d,w)->worker.submit(()->{try{RootShell.Result a=RootShell.run("sm set-force-adoptable true");appendLog(a.combined());RootShell.Result r=RootShell.run("sm partition "+diskId+" private",180);appendLog(r.combined());runOnUiThread(()->toast(r.ok()?"Format selesai":"Format gagal: "+r.combined()));}catch(Exception e){appendLog("FORMAT ERROR: "+e);}runOnUiThread(this::refreshAll);})).show();}
 private void moveApp(AppEntry a,boolean toSd){String target=toSd?volumeUuid:"internal";if(toSd&&target==null){toast("Belum ada adopted SD volume.");return;}new AlertDialog.Builder(this).setTitle(toSd?"Pindahkan ke SD":"Kembalikan ke Internal").setMessage(a.label+"\n"+a.packageName).setNegativeButton("Batal",null).setPositiveButton("Jalankan",(d,w)->worker.submit(()->{try{String cmd="pm move-package "+RootShell.shQuote(a.packageName)+" "+RootShell.shQuote(target);RootShell.Result r=RootShell.run(cmd,180);appendLog(cmd+" → "+r.combined());runOnUiThread(()->toast(r.ok()?"Perintah selesai":"Gagal: "+r.combined()));}catch(Exception e){appendLog("MOVE ERROR: "+e);}loadApps();})).show();}
 private void runRoot(String cmd,boolean refresh){worker.submit(()->{try{RootShell.Result r=RootShell.run(cmd);appendLog(cmd+" → "+r.combined());runOnUiThread(()->toast(r.ok()?"Berhasil":"Gagal: "+r.combined()));}catch(Exception e){appendLog("ERROR: "+e);}if(refresh)runOnUiThread(this::refreshAll);});}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}
